//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Protean.AdminProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.eonic.co.uk/ewAdminProxy", ConfigurationName="AdminProxy.ewAdminProxySoap")]
    public interface ewAdminProxySoap {
        
        // CODEGEN: Generating message contract since element name SoapUrl from namespace http://www.eonic.co.uk/ewAdminProxy is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eonic.co.uk/ewAdminProxy/GetStatus", ReplyAction="*")]
        Protean.AdminProxy.GetStatusResponse GetStatus(Protean.AdminProxy.GetStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eonic.co.uk/ewAdminProxy/GetStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<Protean.AdminProxy.GetStatusResponse> GetStatusAsync(Protean.AdminProxy.GetStatusRequest request);
        
        // CODEGEN: Generating message contract since element name SoapUrl from namespace http://www.eonic.co.uk/ewAdminProxy is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eonic.co.uk/ewAdminProxy/UpgradeDatabase", ReplyAction="*")]
        Protean.AdminProxy.UpgradeDatabaseResponse UpgradeDatabase(Protean.AdminProxy.UpgradeDatabaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eonic.co.uk/ewAdminProxy/UpgradeDatabase", ReplyAction="*")]
        System.Threading.Tasks.Task<Protean.AdminProxy.UpgradeDatabaseResponse> UpgradeDatabaseAsync(Protean.AdminProxy.UpgradeDatabaseRequest request);
        
        // CODEGEN: Generating message contract since element name ServerName from namespace http://www.eonic.co.uk/ewAdminProxy is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eonic.co.uk/ewAdminProxy/GetSiteLicence", ReplyAction="*")]
        Protean.AdminProxy.GetSiteLicenceResponse GetSiteLicence(Protean.AdminProxy.GetSiteLicenceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eonic.co.uk/ewAdminProxy/GetSiteLicence", ReplyAction="*")]
        System.Threading.Tasks.Task<Protean.AdminProxy.GetSiteLicenceResponse> GetSiteLicenceAsync(Protean.AdminProxy.GetSiteLicenceRequest request);
        
        // CODEGEN: Generating message contract since element name ServerName from namespace http://www.eonic.co.uk/ewAdminProxy is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eonic.co.uk/ewAdminProxy/GetThemes", ReplyAction="*")]
        Protean.AdminProxy.GetThemesResponse GetThemes(Protean.AdminProxy.GetThemesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eonic.co.uk/ewAdminProxy/GetThemes", ReplyAction="*")]
        System.Threading.Tasks.Task<Protean.AdminProxy.GetThemesResponse> GetThemesAsync(Protean.AdminProxy.GetThemesRequest request);
        
        // CODEGEN: Generating message contract since element name ServerName from namespace http://www.eonic.co.uk/ewAdminProxy is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eonic.co.uk/ewAdminProxy/GetThemeZip", ReplyAction="*")]
        Protean.AdminProxy.GetThemeZipResponse GetThemeZip(Protean.AdminProxy.GetThemeZipRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eonic.co.uk/ewAdminProxy/GetThemeZip", ReplyAction="*")]
        System.Threading.Tasks.Task<Protean.AdminProxy.GetThemeZipResponse> GetThemeZipAsync(Protean.AdminProxy.GetThemeZipRequest request);
        
        // CODEGEN: Generating message contract since element name ServerName from namespace http://www.eonic.co.uk/ewAdminProxy is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eonic.co.uk/ewAdminProxy/GetModules", ReplyAction="*")]
        Protean.AdminProxy.GetModulesResponse GetModules(Protean.AdminProxy.GetModulesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eonic.co.uk/ewAdminProxy/GetModules", ReplyAction="*")]
        System.Threading.Tasks.Task<Protean.AdminProxy.GetModulesResponse> GetModulesAsync(Protean.AdminProxy.GetModulesRequest request);
        
        // CODEGEN: Generating message contract since element name PageFRef from namespace http://www.eonic.co.uk/ewAdminProxy is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eonic.co.uk/ewAdminProxy/GetPageXml", ReplyAction="*")]
        Protean.AdminProxy.GetPageXmlResponse GetPageXml(Protean.AdminProxy.GetPageXmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eonic.co.uk/ewAdminProxy/GetPageXml", ReplyAction="*")]
        System.Threading.Tasks.Task<Protean.AdminProxy.GetPageXmlResponse> GetPageXmlAsync(Protean.AdminProxy.GetPageXmlRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatus", Namespace="http://www.eonic.co.uk/ewAdminProxy", Order=0)]
        public Protean.AdminProxy.GetStatusRequestBody Body;
        
        public GetStatusRequest() {
        }
        
        public GetStatusRequest(Protean.AdminProxy.GetStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eonic.co.uk/ewAdminProxy")]
    public partial class GetStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SoapUrl;
        
        public GetStatusRequestBody() {
        }
        
        public GetStatusRequestBody(string SoapUrl) {
            this.SoapUrl = SoapUrl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatusResponse", Namespace="http://www.eonic.co.uk/ewAdminProxy", Order=0)]
        public Protean.AdminProxy.GetStatusResponseBody Body;
        
        public GetStatusResponse() {
        }
        
        public GetStatusResponse(Protean.AdminProxy.GetStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eonic.co.uk/ewAdminProxy")]
    public partial class GetStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetStatusResult;
        
        public GetStatusResponseBody() {
        }
        
        public GetStatusResponseBody(System.Xml.Linq.XElement GetStatusResult) {
            this.GetStatusResult = GetStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpgradeDatabaseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpgradeDatabase", Namespace="http://www.eonic.co.uk/ewAdminProxy", Order=0)]
        public Protean.AdminProxy.UpgradeDatabaseRequestBody Body;
        
        public UpgradeDatabaseRequest() {
        }
        
        public UpgradeDatabaseRequest(Protean.AdminProxy.UpgradeDatabaseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eonic.co.uk/ewAdminProxy")]
    public partial class UpgradeDatabaseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SoapUrl;
        
        public UpgradeDatabaseRequestBody() {
        }
        
        public UpgradeDatabaseRequestBody(string SoapUrl) {
            this.SoapUrl = SoapUrl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpgradeDatabaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpgradeDatabaseResponse", Namespace="http://www.eonic.co.uk/ewAdminProxy", Order=0)]
        public Protean.AdminProxy.UpgradeDatabaseResponseBody Body;
        
        public UpgradeDatabaseResponse() {
        }
        
        public UpgradeDatabaseResponse(Protean.AdminProxy.UpgradeDatabaseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eonic.co.uk/ewAdminProxy")]
    public partial class UpgradeDatabaseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement UpgradeDatabaseResult;
        
        public UpgradeDatabaseResponseBody() {
        }
        
        public UpgradeDatabaseResponseBody(System.Xml.Linq.XElement UpgradeDatabaseResult) {
            this.UpgradeDatabaseResult = UpgradeDatabaseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSiteLicenceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSiteLicence", Namespace="http://www.eonic.co.uk/ewAdminProxy", Order=0)]
        public Protean.AdminProxy.GetSiteLicenceRequestBody Body;
        
        public GetSiteLicenceRequest() {
        }
        
        public GetSiteLicenceRequest(Protean.AdminProxy.GetSiteLicenceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eonic.co.uk/ewAdminProxy")]
    public partial class GetSiteLicenceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ServerName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string HTTPhost;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string loggedInUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long PageCount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long ItemCount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public long PlugIns;
        
        public GetSiteLicenceRequestBody() {
        }
        
        public GetSiteLicenceRequestBody(string ServerName, string HTTPhost, string loggedInUser, long PageCount, long ItemCount, long PlugIns) {
            this.ServerName = ServerName;
            this.HTTPhost = HTTPhost;
            this.loggedInUser = loggedInUser;
            this.PageCount = PageCount;
            this.ItemCount = ItemCount;
            this.PlugIns = PlugIns;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSiteLicenceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSiteLicenceResponse", Namespace="http://www.eonic.co.uk/ewAdminProxy", Order=0)]
        public Protean.AdminProxy.GetSiteLicenceResponseBody Body;
        
        public GetSiteLicenceResponse() {
        }
        
        public GetSiteLicenceResponse(Protean.AdminProxy.GetSiteLicenceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eonic.co.uk/ewAdminProxy")]
    public partial class GetSiteLicenceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetSiteLicenceResult;
        
        public GetSiteLicenceResponseBody() {
        }
        
        public GetSiteLicenceResponseBody(System.Xml.Linq.XElement GetSiteLicenceResult) {
            this.GetSiteLicenceResult = GetSiteLicenceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetThemesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetThemes", Namespace="http://www.eonic.co.uk/ewAdminProxy", Order=0)]
        public Protean.AdminProxy.GetThemesRequestBody Body;
        
        public GetThemesRequest() {
        }
        
        public GetThemesRequest(Protean.AdminProxy.GetThemesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eonic.co.uk/ewAdminProxy")]
    public partial class GetThemesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ServerName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string HTTPhost;
        
        public GetThemesRequestBody() {
        }
        
        public GetThemesRequestBody(string ServerName, string HTTPhost) {
            this.ServerName = ServerName;
            this.HTTPhost = HTTPhost;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetThemesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetThemesResponse", Namespace="http://www.eonic.co.uk/ewAdminProxy", Order=0)]
        public Protean.AdminProxy.GetThemesResponseBody Body;
        
        public GetThemesResponse() {
        }
        
        public GetThemesResponse(Protean.AdminProxy.GetThemesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eonic.co.uk/ewAdminProxy")]
    public partial class GetThemesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetThemesResult;
        
        public GetThemesResponseBody() {
        }
        
        public GetThemesResponseBody(System.Xml.Linq.XElement GetThemesResult) {
            this.GetThemesResult = GetThemesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetThemeZipRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetThemeZip", Namespace="http://www.eonic.co.uk/ewAdminProxy", Order=0)]
        public Protean.AdminProxy.GetThemeZipRequestBody Body;
        
        public GetThemeZipRequest() {
        }
        
        public GetThemeZipRequest(Protean.AdminProxy.GetThemeZipRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eonic.co.uk/ewAdminProxy")]
    public partial class GetThemeZipRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ServerName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string HTTPhost;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ThemeName;
        
        public GetThemeZipRequestBody() {
        }
        
        public GetThemeZipRequestBody(string ServerName, string HTTPhost, string ThemeName) {
            this.ServerName = ServerName;
            this.HTTPhost = HTTPhost;
            this.ThemeName = ThemeName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetThemeZipResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetThemeZipResponse", Namespace="http://www.eonic.co.uk/ewAdminProxy", Order=0)]
        public Protean.AdminProxy.GetThemeZipResponseBody Body;
        
        public GetThemeZipResponse() {
        }
        
        public GetThemeZipResponse(Protean.AdminProxy.GetThemeZipResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eonic.co.uk/ewAdminProxy")]
    public partial class GetThemeZipResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GetThemeZipResult;
        
        public GetThemeZipResponseBody() {
        }
        
        public GetThemeZipResponseBody(byte[] GetThemeZipResult) {
            this.GetThemeZipResult = GetThemeZipResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetModulesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetModules", Namespace="http://www.eonic.co.uk/ewAdminProxy", Order=0)]
        public Protean.AdminProxy.GetModulesRequestBody Body;
        
        public GetModulesRequest() {
        }
        
        public GetModulesRequest(Protean.AdminProxy.GetModulesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eonic.co.uk/ewAdminProxy")]
    public partial class GetModulesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ServerName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string HTTPhost;
        
        public GetModulesRequestBody() {
        }
        
        public GetModulesRequestBody(string ServerName, string HTTPhost) {
            this.ServerName = ServerName;
            this.HTTPhost = HTTPhost;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetModulesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetModulesResponse", Namespace="http://www.eonic.co.uk/ewAdminProxy", Order=0)]
        public Protean.AdminProxy.GetModulesResponseBody Body;
        
        public GetModulesResponse() {
        }
        
        public GetModulesResponse(Protean.AdminProxy.GetModulesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eonic.co.uk/ewAdminProxy")]
    public partial class GetModulesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetModulesResult;
        
        public GetModulesResponseBody() {
        }
        
        public GetModulesResponseBody(System.Xml.Linq.XElement GetModulesResult) {
            this.GetModulesResult = GetModulesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPageXmlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPageXml", Namespace="http://www.eonic.co.uk/ewAdminProxy", Order=0)]
        public Protean.AdminProxy.GetPageXmlRequestBody Body;
        
        public GetPageXmlRequest() {
        }
        
        public GetPageXmlRequest(Protean.AdminProxy.GetPageXmlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eonic.co.uk/ewAdminProxy")]
    public partial class GetPageXmlRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PageFRef;
        
        public GetPageXmlRequestBody() {
        }
        
        public GetPageXmlRequestBody(string PageFRef) {
            this.PageFRef = PageFRef;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPageXmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPageXmlResponse", Namespace="http://www.eonic.co.uk/ewAdminProxy", Order=0)]
        public Protean.AdminProxy.GetPageXmlResponseBody Body;
        
        public GetPageXmlResponse() {
        }
        
        public GetPageXmlResponse(Protean.AdminProxy.GetPageXmlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eonic.co.uk/ewAdminProxy")]
    public partial class GetPageXmlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetPageXmlResult;
        
        public GetPageXmlResponseBody() {
        }
        
        public GetPageXmlResponseBody(System.Xml.Linq.XElement GetPageXmlResult) {
            this.GetPageXmlResult = GetPageXmlResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ewAdminProxySoapChannel : Protean.AdminProxy.ewAdminProxySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ewAdminProxySoapClient : System.ServiceModel.ClientBase<Protean.AdminProxy.ewAdminProxySoap>, Protean.AdminProxy.ewAdminProxySoap {
        
        public ewAdminProxySoapClient() {
        }
        
        public ewAdminProxySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ewAdminProxySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ewAdminProxySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ewAdminProxySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Protean.AdminProxy.GetStatusResponse Protean.AdminProxy.ewAdminProxySoap.GetStatus(Protean.AdminProxy.GetStatusRequest request) {
            return base.Channel.GetStatus(request);
        }
        
        public System.Xml.Linq.XElement GetStatus(string SoapUrl) {
            Protean.AdminProxy.GetStatusRequest inValue = new Protean.AdminProxy.GetStatusRequest();
            inValue.Body = new Protean.AdminProxy.GetStatusRequestBody();
            inValue.Body.SoapUrl = SoapUrl;
            Protean.AdminProxy.GetStatusResponse retVal = ((Protean.AdminProxy.ewAdminProxySoap)(this)).GetStatus(inValue);
            return retVal.Body.GetStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Protean.AdminProxy.GetStatusResponse> Protean.AdminProxy.ewAdminProxySoap.GetStatusAsync(Protean.AdminProxy.GetStatusRequest request) {
            return base.Channel.GetStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<Protean.AdminProxy.GetStatusResponse> GetStatusAsync(string SoapUrl) {
            Protean.AdminProxy.GetStatusRequest inValue = new Protean.AdminProxy.GetStatusRequest();
            inValue.Body = new Protean.AdminProxy.GetStatusRequestBody();
            inValue.Body.SoapUrl = SoapUrl;
            return ((Protean.AdminProxy.ewAdminProxySoap)(this)).GetStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Protean.AdminProxy.UpgradeDatabaseResponse Protean.AdminProxy.ewAdminProxySoap.UpgradeDatabase(Protean.AdminProxy.UpgradeDatabaseRequest request) {
            return base.Channel.UpgradeDatabase(request);
        }
        
        public System.Xml.Linq.XElement UpgradeDatabase(string SoapUrl) {
            Protean.AdminProxy.UpgradeDatabaseRequest inValue = new Protean.AdminProxy.UpgradeDatabaseRequest();
            inValue.Body = new Protean.AdminProxy.UpgradeDatabaseRequestBody();
            inValue.Body.SoapUrl = SoapUrl;
            Protean.AdminProxy.UpgradeDatabaseResponse retVal = ((Protean.AdminProxy.ewAdminProxySoap)(this)).UpgradeDatabase(inValue);
            return retVal.Body.UpgradeDatabaseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Protean.AdminProxy.UpgradeDatabaseResponse> Protean.AdminProxy.ewAdminProxySoap.UpgradeDatabaseAsync(Protean.AdminProxy.UpgradeDatabaseRequest request) {
            return base.Channel.UpgradeDatabaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<Protean.AdminProxy.UpgradeDatabaseResponse> UpgradeDatabaseAsync(string SoapUrl) {
            Protean.AdminProxy.UpgradeDatabaseRequest inValue = new Protean.AdminProxy.UpgradeDatabaseRequest();
            inValue.Body = new Protean.AdminProxy.UpgradeDatabaseRequestBody();
            inValue.Body.SoapUrl = SoapUrl;
            return ((Protean.AdminProxy.ewAdminProxySoap)(this)).UpgradeDatabaseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Protean.AdminProxy.GetSiteLicenceResponse Protean.AdminProxy.ewAdminProxySoap.GetSiteLicence(Protean.AdminProxy.GetSiteLicenceRequest request) {
            return base.Channel.GetSiteLicence(request);
        }
        
        public System.Xml.Linq.XElement GetSiteLicence(string ServerName, string HTTPhost, string loggedInUser, long PageCount, long ItemCount, long PlugIns) {
            Protean.AdminProxy.GetSiteLicenceRequest inValue = new Protean.AdminProxy.GetSiteLicenceRequest();
            inValue.Body = new Protean.AdminProxy.GetSiteLicenceRequestBody();
            inValue.Body.ServerName = ServerName;
            inValue.Body.HTTPhost = HTTPhost;
            inValue.Body.loggedInUser = loggedInUser;
            inValue.Body.PageCount = PageCount;
            inValue.Body.ItemCount = ItemCount;
            inValue.Body.PlugIns = PlugIns;
            Protean.AdminProxy.GetSiteLicenceResponse retVal = ((Protean.AdminProxy.ewAdminProxySoap)(this)).GetSiteLicence(inValue);
            return retVal.Body.GetSiteLicenceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Protean.AdminProxy.GetSiteLicenceResponse> Protean.AdminProxy.ewAdminProxySoap.GetSiteLicenceAsync(Protean.AdminProxy.GetSiteLicenceRequest request) {
            return base.Channel.GetSiteLicenceAsync(request);
        }
        
        public System.Threading.Tasks.Task<Protean.AdminProxy.GetSiteLicenceResponse> GetSiteLicenceAsync(string ServerName, string HTTPhost, string loggedInUser, long PageCount, long ItemCount, long PlugIns) {
            Protean.AdminProxy.GetSiteLicenceRequest inValue = new Protean.AdminProxy.GetSiteLicenceRequest();
            inValue.Body = new Protean.AdminProxy.GetSiteLicenceRequestBody();
            inValue.Body.ServerName = ServerName;
            inValue.Body.HTTPhost = HTTPhost;
            inValue.Body.loggedInUser = loggedInUser;
            inValue.Body.PageCount = PageCount;
            inValue.Body.ItemCount = ItemCount;
            inValue.Body.PlugIns = PlugIns;
            return ((Protean.AdminProxy.ewAdminProxySoap)(this)).GetSiteLicenceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Protean.AdminProxy.GetThemesResponse Protean.AdminProxy.ewAdminProxySoap.GetThemes(Protean.AdminProxy.GetThemesRequest request) {
            return base.Channel.GetThemes(request);
        }
        
        public System.Xml.Linq.XElement GetThemes(string ServerName, string HTTPhost) {
            Protean.AdminProxy.GetThemesRequest inValue = new Protean.AdminProxy.GetThemesRequest();
            inValue.Body = new Protean.AdminProxy.GetThemesRequestBody();
            inValue.Body.ServerName = ServerName;
            inValue.Body.HTTPhost = HTTPhost;
            Protean.AdminProxy.GetThemesResponse retVal = ((Protean.AdminProxy.ewAdminProxySoap)(this)).GetThemes(inValue);
            return retVal.Body.GetThemesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Protean.AdminProxy.GetThemesResponse> Protean.AdminProxy.ewAdminProxySoap.GetThemesAsync(Protean.AdminProxy.GetThemesRequest request) {
            return base.Channel.GetThemesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Protean.AdminProxy.GetThemesResponse> GetThemesAsync(string ServerName, string HTTPhost) {
            Protean.AdminProxy.GetThemesRequest inValue = new Protean.AdminProxy.GetThemesRequest();
            inValue.Body = new Protean.AdminProxy.GetThemesRequestBody();
            inValue.Body.ServerName = ServerName;
            inValue.Body.HTTPhost = HTTPhost;
            return ((Protean.AdminProxy.ewAdminProxySoap)(this)).GetThemesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Protean.AdminProxy.GetThemeZipResponse Protean.AdminProxy.ewAdminProxySoap.GetThemeZip(Protean.AdminProxy.GetThemeZipRequest request) {
            return base.Channel.GetThemeZip(request);
        }
        
        public byte[] GetThemeZip(string ServerName, string HTTPhost, string ThemeName) {
            Protean.AdminProxy.GetThemeZipRequest inValue = new Protean.AdminProxy.GetThemeZipRequest();
            inValue.Body = new Protean.AdminProxy.GetThemeZipRequestBody();
            inValue.Body.ServerName = ServerName;
            inValue.Body.HTTPhost = HTTPhost;
            inValue.Body.ThemeName = ThemeName;
            Protean.AdminProxy.GetThemeZipResponse retVal = ((Protean.AdminProxy.ewAdminProxySoap)(this)).GetThemeZip(inValue);
            return retVal.Body.GetThemeZipResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Protean.AdminProxy.GetThemeZipResponse> Protean.AdminProxy.ewAdminProxySoap.GetThemeZipAsync(Protean.AdminProxy.GetThemeZipRequest request) {
            return base.Channel.GetThemeZipAsync(request);
        }
        
        public System.Threading.Tasks.Task<Protean.AdminProxy.GetThemeZipResponse> GetThemeZipAsync(string ServerName, string HTTPhost, string ThemeName) {
            Protean.AdminProxy.GetThemeZipRequest inValue = new Protean.AdminProxy.GetThemeZipRequest();
            inValue.Body = new Protean.AdminProxy.GetThemeZipRequestBody();
            inValue.Body.ServerName = ServerName;
            inValue.Body.HTTPhost = HTTPhost;
            inValue.Body.ThemeName = ThemeName;
            return ((Protean.AdminProxy.ewAdminProxySoap)(this)).GetThemeZipAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Protean.AdminProxy.GetModulesResponse Protean.AdminProxy.ewAdminProxySoap.GetModules(Protean.AdminProxy.GetModulesRequest request) {
            return base.Channel.GetModules(request);
        }
        
        public System.Xml.Linq.XElement GetModules(string ServerName, string HTTPhost) {
            Protean.AdminProxy.GetModulesRequest inValue = new Protean.AdminProxy.GetModulesRequest();
            inValue.Body = new Protean.AdminProxy.GetModulesRequestBody();
            inValue.Body.ServerName = ServerName;
            inValue.Body.HTTPhost = HTTPhost;
            Protean.AdminProxy.GetModulesResponse retVal = ((Protean.AdminProxy.ewAdminProxySoap)(this)).GetModules(inValue);
            return retVal.Body.GetModulesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Protean.AdminProxy.GetModulesResponse> Protean.AdminProxy.ewAdminProxySoap.GetModulesAsync(Protean.AdminProxy.GetModulesRequest request) {
            return base.Channel.GetModulesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Protean.AdminProxy.GetModulesResponse> GetModulesAsync(string ServerName, string HTTPhost) {
            Protean.AdminProxy.GetModulesRequest inValue = new Protean.AdminProxy.GetModulesRequest();
            inValue.Body = new Protean.AdminProxy.GetModulesRequestBody();
            inValue.Body.ServerName = ServerName;
            inValue.Body.HTTPhost = HTTPhost;
            return ((Protean.AdminProxy.ewAdminProxySoap)(this)).GetModulesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Protean.AdminProxy.GetPageXmlResponse Protean.AdminProxy.ewAdminProxySoap.GetPageXml(Protean.AdminProxy.GetPageXmlRequest request) {
            return base.Channel.GetPageXml(request);
        }
        
        public System.Xml.Linq.XElement GetPageXml(string PageFRef) {
            Protean.AdminProxy.GetPageXmlRequest inValue = new Protean.AdminProxy.GetPageXmlRequest();
            inValue.Body = new Protean.AdminProxy.GetPageXmlRequestBody();
            inValue.Body.PageFRef = PageFRef;
            Protean.AdminProxy.GetPageXmlResponse retVal = ((Protean.AdminProxy.ewAdminProxySoap)(this)).GetPageXml(inValue);
            return retVal.Body.GetPageXmlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Protean.AdminProxy.GetPageXmlResponse> Protean.AdminProxy.ewAdminProxySoap.GetPageXmlAsync(Protean.AdminProxy.GetPageXmlRequest request) {
            return base.Channel.GetPageXmlAsync(request);
        }
        
        public System.Threading.Tasks.Task<Protean.AdminProxy.GetPageXmlResponse> GetPageXmlAsync(string PageFRef) {
            Protean.AdminProxy.GetPageXmlRequest inValue = new Protean.AdminProxy.GetPageXmlRequest();
            inValue.Body = new Protean.AdminProxy.GetPageXmlRequestBody();
            inValue.Body.PageFRef = PageFRef;
            return ((Protean.AdminProxy.ewAdminProxySoap)(this)).GetPageXmlAsync(inValue);
        }
    }
}
