'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace eonicweb.com
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://www.eonic.co.uk/ewAdminProxy", ConfigurationName:="eonicweb.com.ewAdminProxySoap")>  _
    Public Interface ewAdminProxySoap
        
        'CODEGEN: Generating message contract since element name SoapUrl from namespace http://www.eonic.co.uk/ewAdminProxy is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.eonic.co.uk/ewAdminProxy/GetStatus", ReplyAction:="*")>  _
        Function GetStatus(ByVal request As eonicweb.com.GetStatusRequest) As eonicweb.com.GetStatusResponse
        
        'CODEGEN: Generating message contract since element name SoapUrl from namespace http://www.eonic.co.uk/ewAdminProxy is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.eonic.co.uk/ewAdminProxy/UpgradeDatabase", ReplyAction:="*")>  _
        Function UpgradeDatabase(ByVal request As eonicweb.com.UpgradeDatabaseRequest) As eonicweb.com.UpgradeDatabaseResponse
        
        'CODEGEN: Generating message contract since element name ServerName from namespace http://www.eonic.co.uk/ewAdminProxy is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.eonic.co.uk/ewAdminProxy/GetSiteLicence", ReplyAction:="*")>  _
        Function GetSiteLicence(ByVal request As eonicweb.com.GetSiteLicenceRequest) As eonicweb.com.GetSiteLicenceResponse
        
        'CODEGEN: Generating message contract since element name ServerName from namespace http://www.eonic.co.uk/ewAdminProxy is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.eonic.co.uk/ewAdminProxy/GetThemes", ReplyAction:="*")>  _
        Function GetThemes(ByVal request As eonicweb.com.GetThemesRequest) As eonicweb.com.GetThemesResponse
        
        'CODEGEN: Generating message contract since element name ServerName from namespace http://www.eonic.co.uk/ewAdminProxy is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.eonic.co.uk/ewAdminProxy/GetThemeZip", ReplyAction:="*")>  _
        Function GetThemeZip(ByVal request As eonicweb.com.GetThemeZipRequest) As eonicweb.com.GetThemeZipResponse
        
        'CODEGEN: Generating message contract since element name ServerName from namespace http://www.eonic.co.uk/ewAdminProxy is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.eonic.co.uk/ewAdminProxy/GetModules", ReplyAction:="*")>  _
        Function GetModules(ByVal request As eonicweb.com.GetModulesRequest) As eonicweb.com.GetModulesResponse
        
        'CODEGEN: Generating message contract since element name PageFRef from namespace http://www.eonic.co.uk/ewAdminProxy is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.eonic.co.uk/ewAdminProxy/GetPageXml", ReplyAction:="*")>  _
        Function GetPageXml(ByVal request As eonicweb.com.GetPageXmlRequest) As eonicweb.com.GetPageXmlResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetStatusRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetStatus", [Namespace]:="http://www.eonic.co.uk/ewAdminProxy", Order:=0)>  _
        Public Body As eonicweb.com.GetStatusRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As eonicweb.com.GetStatusRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.eonic.co.uk/ewAdminProxy")>  _
    Partial Public Class GetStatusRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public SoapUrl As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SoapUrl As String)
            MyBase.New
            Me.SoapUrl = SoapUrl
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetStatusResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetStatusResponse", [Namespace]:="http://www.eonic.co.uk/ewAdminProxy", Order:=0)>  _
        Public Body As eonicweb.com.GetStatusResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As eonicweb.com.GetStatusResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.eonic.co.uk/ewAdminProxy")>  _
    Partial Public Class GetStatusResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetStatusResult As System.Xml.Linq.XElement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetStatusResult As System.Xml.Linq.XElement)
            MyBase.New
            Me.GetStatusResult = GetStatusResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class UpgradeDatabaseRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="UpgradeDatabase", [Namespace]:="http://www.eonic.co.uk/ewAdminProxy", Order:=0)>  _
        Public Body As eonicweb.com.UpgradeDatabaseRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As eonicweb.com.UpgradeDatabaseRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.eonic.co.uk/ewAdminProxy")>  _
    Partial Public Class UpgradeDatabaseRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public SoapUrl As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SoapUrl As String)
            MyBase.New
            Me.SoapUrl = SoapUrl
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class UpgradeDatabaseResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="UpgradeDatabaseResponse", [Namespace]:="http://www.eonic.co.uk/ewAdminProxy", Order:=0)>  _
        Public Body As eonicweb.com.UpgradeDatabaseResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As eonicweb.com.UpgradeDatabaseResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.eonic.co.uk/ewAdminProxy")>  _
    Partial Public Class UpgradeDatabaseResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public UpgradeDatabaseResult As System.Xml.Linq.XElement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal UpgradeDatabaseResult As System.Xml.Linq.XElement)
            MyBase.New
            Me.UpgradeDatabaseResult = UpgradeDatabaseResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetSiteLicenceRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetSiteLicence", [Namespace]:="http://www.eonic.co.uk/ewAdminProxy", Order:=0)>  _
        Public Body As eonicweb.com.GetSiteLicenceRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As eonicweb.com.GetSiteLicenceRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.eonic.co.uk/ewAdminProxy")>  _
    Partial Public Class GetSiteLicenceRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ServerName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public HTTPhost As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public loggedInUser As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
        Public PageCount As Long
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=4)>  _
        Public ItemCount As Long
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=5)>  _
        Public PlugIns As Long
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ServerName As String, ByVal HTTPhost As String, ByVal loggedInUser As String, ByVal PageCount As Long, ByVal ItemCount As Long, ByVal PlugIns As Long)
            MyBase.New
            Me.ServerName = ServerName
            Me.HTTPhost = HTTPhost
            Me.loggedInUser = loggedInUser
            Me.PageCount = PageCount
            Me.ItemCount = ItemCount
            Me.PlugIns = PlugIns
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetSiteLicenceResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetSiteLicenceResponse", [Namespace]:="http://www.eonic.co.uk/ewAdminProxy", Order:=0)>  _
        Public Body As eonicweb.com.GetSiteLicenceResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As eonicweb.com.GetSiteLicenceResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.eonic.co.uk/ewAdminProxy")>  _
    Partial Public Class GetSiteLicenceResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetSiteLicenceResult As System.Xml.Linq.XElement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetSiteLicenceResult As System.Xml.Linq.XElement)
            MyBase.New
            Me.GetSiteLicenceResult = GetSiteLicenceResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetThemesRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetThemes", [Namespace]:="http://www.eonic.co.uk/ewAdminProxy", Order:=0)>  _
        Public Body As eonicweb.com.GetThemesRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As eonicweb.com.GetThemesRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.eonic.co.uk/ewAdminProxy")>  _
    Partial Public Class GetThemesRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ServerName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public HTTPhost As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ServerName As String, ByVal HTTPhost As String)
            MyBase.New
            Me.ServerName = ServerName
            Me.HTTPhost = HTTPhost
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetThemesResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetThemesResponse", [Namespace]:="http://www.eonic.co.uk/ewAdminProxy", Order:=0)>  _
        Public Body As eonicweb.com.GetThemesResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As eonicweb.com.GetThemesResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.eonic.co.uk/ewAdminProxy")>  _
    Partial Public Class GetThemesResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetThemesResult As System.Xml.Linq.XElement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetThemesResult As System.Xml.Linq.XElement)
            MyBase.New
            Me.GetThemesResult = GetThemesResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetThemeZipRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetThemeZip", [Namespace]:="http://www.eonic.co.uk/ewAdminProxy", Order:=0)>  _
        Public Body As eonicweb.com.GetThemeZipRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As eonicweb.com.GetThemeZipRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.eonic.co.uk/ewAdminProxy")>  _
    Partial Public Class GetThemeZipRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ServerName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public HTTPhost As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public ThemeName As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ServerName As String, ByVal HTTPhost As String, ByVal ThemeName As String)
            MyBase.New
            Me.ServerName = ServerName
            Me.HTTPhost = HTTPhost
            Me.ThemeName = ThemeName
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetThemeZipResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetThemeZipResponse", [Namespace]:="http://www.eonic.co.uk/ewAdminProxy", Order:=0)>  _
        Public Body As eonicweb.com.GetThemeZipResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As eonicweb.com.GetThemeZipResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.eonic.co.uk/ewAdminProxy")>  _
    Partial Public Class GetThemeZipResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetThemeZipResult() As Byte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetThemeZipResult() As Byte)
            MyBase.New
            Me.GetThemeZipResult = GetThemeZipResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetModulesRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetModules", [Namespace]:="http://www.eonic.co.uk/ewAdminProxy", Order:=0)>  _
        Public Body As eonicweb.com.GetModulesRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As eonicweb.com.GetModulesRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.eonic.co.uk/ewAdminProxy")>  _
    Partial Public Class GetModulesRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ServerName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public HTTPhost As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ServerName As String, ByVal HTTPhost As String)
            MyBase.New
            Me.ServerName = ServerName
            Me.HTTPhost = HTTPhost
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetModulesResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetModulesResponse", [Namespace]:="http://www.eonic.co.uk/ewAdminProxy", Order:=0)>  _
        Public Body As eonicweb.com.GetModulesResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As eonicweb.com.GetModulesResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.eonic.co.uk/ewAdminProxy")>  _
    Partial Public Class GetModulesResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetModulesResult As System.Xml.Linq.XElement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetModulesResult As System.Xml.Linq.XElement)
            MyBase.New
            Me.GetModulesResult = GetModulesResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetPageXmlRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetPageXml", [Namespace]:="http://www.eonic.co.uk/ewAdminProxy", Order:=0)>  _
        Public Body As eonicweb.com.GetPageXmlRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As eonicweb.com.GetPageXmlRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.eonic.co.uk/ewAdminProxy")>  _
    Partial Public Class GetPageXmlRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public PageFRef As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal PageFRef As String)
            MyBase.New
            Me.PageFRef = PageFRef
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetPageXmlResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetPageXmlResponse", [Namespace]:="http://www.eonic.co.uk/ewAdminProxy", Order:=0)>  _
        Public Body As eonicweb.com.GetPageXmlResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As eonicweb.com.GetPageXmlResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.eonic.co.uk/ewAdminProxy")>  _
    Partial Public Class GetPageXmlResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetPageXmlResult As System.Xml.Linq.XElement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetPageXmlResult As System.Xml.Linq.XElement)
            MyBase.New
            Me.GetPageXmlResult = GetPageXmlResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ewAdminProxySoapChannel
        Inherits eonicweb.com.ewAdminProxySoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ewAdminProxySoapClient
        Inherits System.ServiceModel.ClientBase(Of eonicweb.com.ewAdminProxySoap)
        Implements eonicweb.com.ewAdminProxySoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function eonicweb_com_ewAdminProxySoap_GetStatus(ByVal request As eonicweb.com.GetStatusRequest) As eonicweb.com.GetStatusResponse Implements eonicweb.com.ewAdminProxySoap.GetStatus
            Return MyBase.Channel.GetStatus(request)
        End Function
        
        Public Function GetStatus(ByVal SoapUrl As String) As System.Xml.Linq.XElement
            Dim inValue As eonicweb.com.GetStatusRequest = New eonicweb.com.GetStatusRequest()
            inValue.Body = New eonicweb.com.GetStatusRequestBody()
            inValue.Body.SoapUrl = SoapUrl
            Dim retVal As eonicweb.com.GetStatusResponse = CType(Me,eonicweb.com.ewAdminProxySoap).GetStatus(inValue)
            Return retVal.Body.GetStatusResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function eonicweb_com_ewAdminProxySoap_UpgradeDatabase(ByVal request As eonicweb.com.UpgradeDatabaseRequest) As eonicweb.com.UpgradeDatabaseResponse Implements eonicweb.com.ewAdminProxySoap.UpgradeDatabase
            Return MyBase.Channel.UpgradeDatabase(request)
        End Function
        
        Public Function UpgradeDatabase(ByVal SoapUrl As String) As System.Xml.Linq.XElement
            Dim inValue As eonicweb.com.UpgradeDatabaseRequest = New eonicweb.com.UpgradeDatabaseRequest()
            inValue.Body = New eonicweb.com.UpgradeDatabaseRequestBody()
            inValue.Body.SoapUrl = SoapUrl
            Dim retVal As eonicweb.com.UpgradeDatabaseResponse = CType(Me,eonicweb.com.ewAdminProxySoap).UpgradeDatabase(inValue)
            Return retVal.Body.UpgradeDatabaseResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function eonicweb_com_ewAdminProxySoap_GetSiteLicence(ByVal request As eonicweb.com.GetSiteLicenceRequest) As eonicweb.com.GetSiteLicenceResponse Implements eonicweb.com.ewAdminProxySoap.GetSiteLicence
            Return MyBase.Channel.GetSiteLicence(request)
        End Function
        
        Public Function GetSiteLicence(ByVal ServerName As String, ByVal HTTPhost As String, ByVal loggedInUser As String, ByVal PageCount As Long, ByVal ItemCount As Long, ByVal PlugIns As Long) As System.Xml.Linq.XElement
            Dim inValue As eonicweb.com.GetSiteLicenceRequest = New eonicweb.com.GetSiteLicenceRequest()
            inValue.Body = New eonicweb.com.GetSiteLicenceRequestBody()
            inValue.Body.ServerName = ServerName
            inValue.Body.HTTPhost = HTTPhost
            inValue.Body.loggedInUser = loggedInUser
            inValue.Body.PageCount = PageCount
            inValue.Body.ItemCount = ItemCount
            inValue.Body.PlugIns = PlugIns
            Dim retVal As eonicweb.com.GetSiteLicenceResponse = CType(Me,eonicweb.com.ewAdminProxySoap).GetSiteLicence(inValue)
            Return retVal.Body.GetSiteLicenceResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function eonicweb_com_ewAdminProxySoap_GetThemes(ByVal request As eonicweb.com.GetThemesRequest) As eonicweb.com.GetThemesResponse Implements eonicweb.com.ewAdminProxySoap.GetThemes
            Return MyBase.Channel.GetThemes(request)
        End Function
        
        Public Function GetThemes(ByVal ServerName As String, ByVal HTTPhost As String) As System.Xml.Linq.XElement
            Dim inValue As eonicweb.com.GetThemesRequest = New eonicweb.com.GetThemesRequest()
            inValue.Body = New eonicweb.com.GetThemesRequestBody()
            inValue.Body.ServerName = ServerName
            inValue.Body.HTTPhost = HTTPhost
            Dim retVal As eonicweb.com.GetThemesResponse = CType(Me,eonicweb.com.ewAdminProxySoap).GetThemes(inValue)
            Return retVal.Body.GetThemesResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function eonicweb_com_ewAdminProxySoap_GetThemeZip(ByVal request As eonicweb.com.GetThemeZipRequest) As eonicweb.com.GetThemeZipResponse Implements eonicweb.com.ewAdminProxySoap.GetThemeZip
            Return MyBase.Channel.GetThemeZip(request)
        End Function
        
        Public Function GetThemeZip(ByVal ServerName As String, ByVal HTTPhost As String, ByVal ThemeName As String) As Byte()
            Dim inValue As eonicweb.com.GetThemeZipRequest = New eonicweb.com.GetThemeZipRequest()
            inValue.Body = New eonicweb.com.GetThemeZipRequestBody()
            inValue.Body.ServerName = ServerName
            inValue.Body.HTTPhost = HTTPhost
            inValue.Body.ThemeName = ThemeName
            Dim retVal As eonicweb.com.GetThemeZipResponse = CType(Me,eonicweb.com.ewAdminProxySoap).GetThemeZip(inValue)
            Return retVal.Body.GetThemeZipResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function eonicweb_com_ewAdminProxySoap_GetModules(ByVal request As eonicweb.com.GetModulesRequest) As eonicweb.com.GetModulesResponse Implements eonicweb.com.ewAdminProxySoap.GetModules
            Return MyBase.Channel.GetModules(request)
        End Function
        
        Public Function GetModules(ByVal ServerName As String, ByVal HTTPhost As String) As System.Xml.Linq.XElement
            Dim inValue As eonicweb.com.GetModulesRequest = New eonicweb.com.GetModulesRequest()
            inValue.Body = New eonicweb.com.GetModulesRequestBody()
            inValue.Body.ServerName = ServerName
            inValue.Body.HTTPhost = HTTPhost
            Dim retVal As eonicweb.com.GetModulesResponse = CType(Me,eonicweb.com.ewAdminProxySoap).GetModules(inValue)
            Return retVal.Body.GetModulesResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function eonicweb_com_ewAdminProxySoap_GetPageXml(ByVal request As eonicweb.com.GetPageXmlRequest) As eonicweb.com.GetPageXmlResponse Implements eonicweb.com.ewAdminProxySoap.GetPageXml
            Return MyBase.Channel.GetPageXml(request)
        End Function
        
        Public Function GetPageXml(ByVal PageFRef As String) As System.Xml.Linq.XElement
            Dim inValue As eonicweb.com.GetPageXmlRequest = New eonicweb.com.GetPageXmlRequest()
            inValue.Body = New eonicweb.com.GetPageXmlRequestBody()
            inValue.Body.PageFRef = PageFRef
            Dim retVal As eonicweb.com.GetPageXmlResponse = CType(Me,eonicweb.com.ewAdminProxySoap).GetPageXml(inValue)
            Return retVal.Body.GetPageXmlResult
        End Function
    End Class
End Namespace
