'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Paypoint
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="https://www.secpay.com/java-bin/services/SECCardService", ConfigurationName:="Paypoint.SECVPN")>  _
    Public Interface SECVPN
        
        'CODEGEN: Generating message contract since the wrapper namespace (http://secvpn.secpay.com) of message refundCardFullRequest does not match the default value (https://www.secpay.com/java-bin/services/SECCardService)
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function refundCardFull(ByVal request As Paypoint.refundCardFullRequest) As Paypoint.refundCardFullResponse
        
        'CODEGEN: Generating message contract since the wrapper namespace (http://secvpn.secpay.com) of message releaseCardFullRequest does not match the default value (https://www.secpay.com/java-bin/services/SECCardService)
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function releaseCardFull(ByVal request As Paypoint.releaseCardFullRequest) As Paypoint.releaseCardFullResponse
        
        'CODEGEN: Generating message contract since the wrapper namespace (http://secvpn.secpay.com) of message repeatCardFullAddrRequest does not match the default value (https://www.secpay.com/java-bin/services/SECCardService)
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function repeatCardFullAddr(ByVal request As Paypoint.repeatCardFullAddrRequest) As Paypoint.repeatCardFullAddrResponse
        
        'CODEGEN: Generating message contract since the wrapper namespace (http://secvpn.secpay.com) of message repeatCardFullRequest does not match the default value (https://www.secpay.com/java-bin/services/SECCardService)
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function repeatCardFull(ByVal request As Paypoint.repeatCardFullRequest) As Paypoint.repeatCardFullResponse
        
        'CODEGEN: Generating message contract since the wrapper namespace (http://secvpn.secpay.com) of message validateCardFullRequest does not match the default value (https://www.secpay.com/java-bin/services/SECCardService)
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function validateCardFull(ByVal request As Paypoint.validateCardFullRequest) As Paypoint.validateCardFullResponse
        
        'CODEGEN: Generating message contract since the wrapper namespace (http://secvpn.secpay.com) of message threeDSecureEnrolmentRequestRequest does not match the default value (https://www.secpay.com/java-bin/services/SECCardService)
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function threeDSecureEnrolmentRequest(ByVal request As Paypoint.threeDSecureEnrolmentRequestRequest) As Paypoint.threeDSecureEnrolmentRequestResponse
        
        'CODEGEN: Generating message contract since the wrapper namespace (http://secvpn.secpay.com) of message threeDSecureAuthorisationRequestRequest does not match the default value (https://www.secpay.com/java-bin/services/SECCardService)
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function threeDSecureAuthorisationRequest(ByVal request As Paypoint.threeDSecureAuthorisationRequestRequest) As Paypoint.threeDSecureAuthorisationRequestResponse
        
        'CODEGEN: Generating message contract since the wrapper namespace (http://secvpn.secpay.com) of message getReportRequest does not match the default value (https://www.secpay.com/java-bin/services/SECCardService)
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function getReport(ByVal request As Paypoint.getReportRequest) As Paypoint.getReportResponse
        
        'CODEGEN: Generating message contract since the wrapper namespace (http://secvpn.secpay.com) of message getTZReportRequest does not match the default value (https://www.secpay.com/java-bin/services/SECCardService)
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function getTZReport(ByVal request As Paypoint.getTZReportRequest) As Paypoint.getTZReportResponse
        
        'CODEGEN: Generating message contract since the wrapper namespace (http://secvpn.secpay.com) of message performTransactionViaAlternatePaymentMethodRequest does not match the default value (https://www.secpay.com/java-bin/services/SECCardService)
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function performTransactionViaAlternatePaymentMethod(ByVal request As Paypoint.performTransactionViaAlternatePaymentMethodRequest) As Paypoint.performTransactionViaAlternatePaymentMethodResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="refundCardFull", WrapperNamespace:="http://secvpn.secpay.com", IsWrapped:=true)>  _
    Partial Public Class refundCardFullRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public mid As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public vpn_pswd As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public trans_id As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public amount As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=4)>  _
        Public remote_pswd As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=5)>  _
        Public new_trans_id As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal mid As String, ByVal vpn_pswd As String, ByVal trans_id As String, ByVal amount As String, ByVal remote_pswd As String, ByVal new_trans_id As String)
            MyBase.New
            Me.mid = mid
            Me.vpn_pswd = vpn_pswd
            Me.trans_id = trans_id
            Me.amount = amount
            Me.remote_pswd = remote_pswd
            Me.new_trans_id = new_trans_id
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="refundCardFullResponse", WrapperNamespace:="https://www.secpay.com/java-bin/services/SECCardService", IsWrapped:=true)>  _
    Partial Public Class refundCardFullResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public refundCardFullReturn As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal refundCardFullReturn As String)
            MyBase.New
            Me.refundCardFullReturn = refundCardFullReturn
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="releaseCardFull", WrapperNamespace:="http://secvpn.secpay.com", IsWrapped:=true)>  _
    Partial Public Class releaseCardFullRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public mid As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public vpn_pswd As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public trans_id As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public amount As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=4)>  _
        Public remote_pswd As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=5)>  _
        Public new_trans_id As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal mid As String, ByVal vpn_pswd As String, ByVal trans_id As String, ByVal amount As String, ByVal remote_pswd As String, ByVal new_trans_id As String)
            MyBase.New
            Me.mid = mid
            Me.vpn_pswd = vpn_pswd
            Me.trans_id = trans_id
            Me.amount = amount
            Me.remote_pswd = remote_pswd
            Me.new_trans_id = new_trans_id
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="releaseCardFullResponse", WrapperNamespace:="https://www.secpay.com/java-bin/services/SECCardService", IsWrapped:=true)>  _
    Partial Public Class releaseCardFullResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public releaseCardFullReturn As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal releaseCardFullReturn As String)
            MyBase.New
            Me.releaseCardFullReturn = releaseCardFullReturn
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="repeatCardFullAddr", WrapperNamespace:="http://secvpn.secpay.com", IsWrapped:=true)>  _
    Partial Public Class repeatCardFullAddrRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public mid As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public vpn_pswd As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public trans_id As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public amount As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=4)>  _
        Public remote_pswd As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=5)>  _
        Public new_trans_id As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=6)>  _
        Public exp_date As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=7)>  _
        Public order As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=8)>  _
        Public bill As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=9)>  _
        Public ship As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=10)>  _
        Public options As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal mid As String, ByVal vpn_pswd As String, ByVal trans_id As String, ByVal amount As String, ByVal remote_pswd As String, ByVal new_trans_id As String, ByVal exp_date As String, ByVal order As String, ByVal bill As String, ByVal ship As String, ByVal options As String)
            MyBase.New
            Me.mid = mid
            Me.vpn_pswd = vpn_pswd
            Me.trans_id = trans_id
            Me.amount = amount
            Me.remote_pswd = remote_pswd
            Me.new_trans_id = new_trans_id
            Me.exp_date = exp_date
            Me.order = order
            Me.bill = bill
            Me.ship = ship
            Me.options = options
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="repeatCardFullAddrResponse", WrapperNamespace:="https://www.secpay.com/java-bin/services/SECCardService", IsWrapped:=true)>  _
    Partial Public Class repeatCardFullAddrResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public repeatCardFullAddrReturn As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal repeatCardFullAddrReturn As String)
            MyBase.New
            Me.repeatCardFullAddrReturn = repeatCardFullAddrReturn
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="repeatCardFull", WrapperNamespace:="http://secvpn.secpay.com", IsWrapped:=true)>  _
    Partial Public Class repeatCardFullRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public mid As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public vpn_pswd As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public trans_id As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public amount As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=4)>  _
        Public remote_pswd As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=5)>  _
        Public new_trans_id As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=6)>  _
        Public exp_date As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=7)>  _
        Public order As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal mid As String, ByVal vpn_pswd As String, ByVal trans_id As String, ByVal amount As String, ByVal remote_pswd As String, ByVal new_trans_id As String, ByVal exp_date As String, ByVal order As String)
            MyBase.New
            Me.mid = mid
            Me.vpn_pswd = vpn_pswd
            Me.trans_id = trans_id
            Me.amount = amount
            Me.remote_pswd = remote_pswd
            Me.new_trans_id = new_trans_id
            Me.exp_date = exp_date
            Me.order = order
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="repeatCardFullResponse", WrapperNamespace:="https://www.secpay.com/java-bin/services/SECCardService", IsWrapped:=true)>  _
    Partial Public Class repeatCardFullResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public repeatCardFullReturn As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal repeatCardFullReturn As String)
            MyBase.New
            Me.repeatCardFullReturn = repeatCardFullReturn
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="validateCardFull", WrapperNamespace:="http://secvpn.secpay.com", IsWrapped:=true)>  _
    Partial Public Class validateCardFullRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public mid As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public vpn_pswd As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public trans_id As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public ip As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=4)>  _
        Public name As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=5)>  _
        Public card_number As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=6)>  _
        Public amount As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=7)>  _
        Public expiry_date As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=8)>  _
        Public issue_number As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=9)>  _
        Public start_date As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=10)>  _
        Public order As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=11)>  _
        Public shipping As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=12)>  _
        Public billing As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=13)>  _
        Public options As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal mid As String, ByVal vpn_pswd As String, ByVal trans_id As String, ByVal ip As String, ByVal name As String, ByVal card_number As String, ByVal amount As String, ByVal expiry_date As String, ByVal issue_number As String, ByVal start_date As String, ByVal order As String, ByVal shipping As String, ByVal billing As String, ByVal options As String)
            MyBase.New
            Me.mid = mid
            Me.vpn_pswd = vpn_pswd
            Me.trans_id = trans_id
            Me.ip = ip
            Me.name = name
            Me.card_number = card_number
            Me.amount = amount
            Me.expiry_date = expiry_date
            Me.issue_number = issue_number
            Me.start_date = start_date
            Me.order = order
            Me.shipping = shipping
            Me.billing = billing
            Me.options = options
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="validateCardFullResponse", WrapperNamespace:="https://www.secpay.com/java-bin/services/SECCardService", IsWrapped:=true)>  _
    Partial Public Class validateCardFullResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public validateCardFullReturn As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal validateCardFullReturn As String)
            MyBase.New
            Me.validateCardFullReturn = validateCardFullReturn
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="threeDSecureEnrolmentRequest", WrapperNamespace:="http://secvpn.secpay.com", IsWrapped:=true)>  _
    Partial Public Class threeDSecureEnrolmentRequestRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public mid As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public vpn_pswd As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public trans_id As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public ip As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=4)>  _
        Public name As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=5)>  _
        Public card_number As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=6)>  _
        Public amount As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=7)>  _
        Public expiry_date As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=8)>  _
        Public issue_number As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=9)>  _
        Public start_date As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=10)>  _
        Public order As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=11)>  _
        Public shipping As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=12)>  _
        Public billing As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=13)>  _
        Public options As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=14)>  _
        Public device_category As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=15)>  _
        Public accept_headers As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=16)>  _
        Public user_agent As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=17)>  _
        Public mpi_merchant_name As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=18)>  _
        Public mpi_merchant_url As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=19)>  _
        Public mpi_description As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=20)>  _
        Public purchaseRecurringFrequency As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=21)>  _
        Public purchaseRecurringExpiry As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=22)>  _
        Public purchaseInstallments As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New( _
                    ByVal mid As String,  _
                    ByVal vpn_pswd As String,  _
                    ByVal trans_id As String,  _
                    ByVal ip As String,  _
                    ByVal name As String,  _
                    ByVal card_number As String,  _
                    ByVal amount As String,  _
                    ByVal expiry_date As String,  _
                    ByVal issue_number As String,  _
                    ByVal start_date As String,  _
                    ByVal order As String,  _
                    ByVal shipping As String,  _
                    ByVal billing As String,  _
                    ByVal options As String,  _
                    ByVal device_category As String,  _
                    ByVal accept_headers As String,  _
                    ByVal user_agent As String,  _
                    ByVal mpi_merchant_name As String,  _
                    ByVal mpi_merchant_url As String,  _
                    ByVal mpi_description As String,  _
                    ByVal purchaseRecurringFrequency As String,  _
                    ByVal purchaseRecurringExpiry As String,  _
                    ByVal purchaseInstallments As String)
            MyBase.New
            Me.mid = mid
            Me.vpn_pswd = vpn_pswd
            Me.trans_id = trans_id
            Me.ip = ip
            Me.name = name
            Me.card_number = card_number
            Me.amount = amount
            Me.expiry_date = expiry_date
            Me.issue_number = issue_number
            Me.start_date = start_date
            Me.order = order
            Me.shipping = shipping
            Me.billing = billing
            Me.options = options
            Me.device_category = device_category
            Me.accept_headers = accept_headers
            Me.user_agent = user_agent
            Me.mpi_merchant_name = mpi_merchant_name
            Me.mpi_merchant_url = mpi_merchant_url
            Me.mpi_description = mpi_description
            Me.purchaseRecurringFrequency = purchaseRecurringFrequency
            Me.purchaseRecurringExpiry = purchaseRecurringExpiry
            Me.purchaseInstallments = purchaseInstallments
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="threeDSecureEnrolmentRequestResponse", WrapperNamespace:="https://www.secpay.com/java-bin/services/SECCardService", IsWrapped:=true)>  _
    Partial Public Class threeDSecureEnrolmentRequestResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public threeDSecureEnrolmentRequestReturn As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal threeDSecureEnrolmentRequestReturn As String)
            MyBase.New
            Me.threeDSecureEnrolmentRequestReturn = threeDSecureEnrolmentRequestReturn
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="threeDSecureAuthorisationRequest", WrapperNamespace:="http://secvpn.secpay.com", IsWrapped:=true)>  _
    Partial Public Class threeDSecureAuthorisationRequestRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public mid As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public vpn_pswd As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public trans_id As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public md As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=4)>  _
        Public paRes As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=5)>  _
        Public options As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal mid As String, ByVal vpn_pswd As String, ByVal trans_id As String, ByVal md As String, ByVal paRes As String, ByVal options As String)
            MyBase.New
            Me.mid = mid
            Me.vpn_pswd = vpn_pswd
            Me.trans_id = trans_id
            Me.md = md
            Me.paRes = paRes
            Me.options = options
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="threeDSecureAuthorisationRequestResponse", WrapperNamespace:="https://www.secpay.com/java-bin/services/SECCardService", IsWrapped:=true)>  _
    Partial Public Class threeDSecureAuthorisationRequestResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public threeDSecureAuthorisationRequestReturn As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal threeDSecureAuthorisationRequestReturn As String)
            MyBase.New
            Me.threeDSecureAuthorisationRequestReturn = threeDSecureAuthorisationRequestReturn
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getReport", WrapperNamespace:="http://secvpn.secpay.com", IsWrapped:=true)>  _
    Partial Public Class getReportRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public mid As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public vpn_pswd As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public remote_pswd As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public report_type As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=4)>  _
        Public cond_type As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=5)>  _
        Public condition As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=6)>  _
        Public currency As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=7)>  _
        Public predicate As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=8)>  _
        Public html As Boolean
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=9)>  _
        Public showErrs As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal mid As String, ByVal vpn_pswd As String, ByVal remote_pswd As String, ByVal report_type As String, ByVal cond_type As String, ByVal condition As String, ByVal currency As String, ByVal predicate As String, ByVal html As Boolean, ByVal showErrs As Boolean)
            MyBase.New
            Me.mid = mid
            Me.vpn_pswd = vpn_pswd
            Me.remote_pswd = remote_pswd
            Me.report_type = report_type
            Me.cond_type = cond_type
            Me.condition = condition
            Me.currency = currency
            Me.predicate = predicate
            Me.html = html
            Me.showErrs = showErrs
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getReportResponse", WrapperNamespace:="https://www.secpay.com/java-bin/services/SECCardService", IsWrapped:=true)>  _
    Partial Public Class getReportResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public getReportReturn As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal getReportReturn As String)
            MyBase.New
            Me.getReportReturn = getReportReturn
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getTZReport", WrapperNamespace:="http://secvpn.secpay.com", IsWrapped:=true)>  _
    Partial Public Class getTZReportRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public mid As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public vpn_pswd As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public remote_pswd As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public report_type As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=4)>  _
        Public cond_type As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=5)>  _
        Public condition As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=6)>  _
        Public currency As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=7)>  _
        Public predicate As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=8)>  _
        Public html As Boolean
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=9)>  _
        Public showErrs As Boolean
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=10)>  _
        Public tz As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal mid As String, ByVal vpn_pswd As String, ByVal remote_pswd As String, ByVal report_type As String, ByVal cond_type As String, ByVal condition As String, ByVal currency As String, ByVal predicate As String, ByVal html As Boolean, ByVal showErrs As Boolean, ByVal tz As String)
            MyBase.New
            Me.mid = mid
            Me.vpn_pswd = vpn_pswd
            Me.remote_pswd = remote_pswd
            Me.report_type = report_type
            Me.cond_type = cond_type
            Me.condition = condition
            Me.currency = currency
            Me.predicate = predicate
            Me.html = html
            Me.showErrs = showErrs
            Me.tz = tz
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getTZReportResponse", WrapperNamespace:="https://www.secpay.com/java-bin/services/SECCardService", IsWrapped:=true)>  _
    Partial Public Class getTZReportResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public getTZReportReturn As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal getTZReportReturn As String)
            MyBase.New
            Me.getTZReportReturn = getTZReportReturn
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="performTransactionViaAlternatePaymentMethod", WrapperNamespace:="http://secvpn.secpay.com", IsWrapped:=true)>  _
    Partial Public Class performTransactionViaAlternatePaymentMethodRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public mid As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public vpn_pswd As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public paymentOrganisation As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public paymentMethod As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=4)>  _
        Public paymentType As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=5)>  _
        Public paymentRequestType As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=6)>  _
        Public trans_id As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=7)>  _
        Public amount As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=8)>  _
        Public currency As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=9)>  _
        Public options As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal mid As String, ByVal vpn_pswd As String, ByVal paymentOrganisation As String, ByVal paymentMethod As String, ByVal paymentType As String, ByVal paymentRequestType As String, ByVal trans_id As String, ByVal amount As String, ByVal currency As String, ByVal options As String)
            MyBase.New
            Me.mid = mid
            Me.vpn_pswd = vpn_pswd
            Me.paymentOrganisation = paymentOrganisation
            Me.paymentMethod = paymentMethod
            Me.paymentType = paymentType
            Me.paymentRequestType = paymentRequestType
            Me.trans_id = trans_id
            Me.amount = amount
            Me.currency = currency
            Me.options = options
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="performTransactionViaAlternatePaymentMethodResponse", WrapperNamespace:="https://www.secpay.com/java-bin/services/SECCardService", IsWrapped:=true)>  _
    Partial Public Class performTransactionViaAlternatePaymentMethodResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public performTransactionViaAlternatePaymentMethodReturn As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal performTransactionViaAlternatePaymentMethodReturn As String)
            MyBase.New
            Me.performTransactionViaAlternatePaymentMethodReturn = performTransactionViaAlternatePaymentMethodReturn
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface SECVPNChannel
        Inherits Paypoint.SECVPN, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SECVPNClient
        Inherits System.ServiceModel.ClientBase(Of Paypoint.SECVPN)
        Implements Paypoint.SECVPN
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Paypoint_SECVPN_refundCardFull(ByVal request As Paypoint.refundCardFullRequest) As Paypoint.refundCardFullResponse Implements Paypoint.SECVPN.refundCardFull
            Return MyBase.Channel.refundCardFull(request)
        End Function
        
        Public Function refundCardFull(ByVal mid As String, ByVal vpn_pswd As String, ByVal trans_id As String, ByVal amount As String, ByVal remote_pswd As String, ByVal new_trans_id As String) As String
            Dim inValue As Paypoint.refundCardFullRequest = New Paypoint.refundCardFullRequest()
            inValue.mid = mid
            inValue.vpn_pswd = vpn_pswd
            inValue.trans_id = trans_id
            inValue.amount = amount
            inValue.remote_pswd = remote_pswd
            inValue.new_trans_id = new_trans_id
            Dim retVal As Paypoint.refundCardFullResponse = CType(Me,Paypoint.SECVPN).refundCardFull(inValue)
            Return retVal.refundCardFullReturn
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Paypoint_SECVPN_releaseCardFull(ByVal request As Paypoint.releaseCardFullRequest) As Paypoint.releaseCardFullResponse Implements Paypoint.SECVPN.releaseCardFull
            Return MyBase.Channel.releaseCardFull(request)
        End Function
        
        Public Function releaseCardFull(ByVal mid As String, ByVal vpn_pswd As String, ByVal trans_id As String, ByVal amount As String, ByVal remote_pswd As String, ByVal new_trans_id As String) As String
            Dim inValue As Paypoint.releaseCardFullRequest = New Paypoint.releaseCardFullRequest()
            inValue.mid = mid
            inValue.vpn_pswd = vpn_pswd
            inValue.trans_id = trans_id
            inValue.amount = amount
            inValue.remote_pswd = remote_pswd
            inValue.new_trans_id = new_trans_id
            Dim retVal As Paypoint.releaseCardFullResponse = CType(Me,Paypoint.SECVPN).releaseCardFull(inValue)
            Return retVal.releaseCardFullReturn
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Paypoint_SECVPN_repeatCardFullAddr(ByVal request As Paypoint.repeatCardFullAddrRequest) As Paypoint.repeatCardFullAddrResponse Implements Paypoint.SECVPN.repeatCardFullAddr
            Return MyBase.Channel.repeatCardFullAddr(request)
        End Function
        
        Public Function repeatCardFullAddr(ByVal mid As String, ByVal vpn_pswd As String, ByVal trans_id As String, ByVal amount As String, ByVal remote_pswd As String, ByVal new_trans_id As String, ByVal exp_date As String, ByVal order As String, ByVal bill As String, ByVal ship As String, ByVal options As String) As String
            Dim inValue As Paypoint.repeatCardFullAddrRequest = New Paypoint.repeatCardFullAddrRequest()
            inValue.mid = mid
            inValue.vpn_pswd = vpn_pswd
            inValue.trans_id = trans_id
            inValue.amount = amount
            inValue.remote_pswd = remote_pswd
            inValue.new_trans_id = new_trans_id
            inValue.exp_date = exp_date
            inValue.order = order
            inValue.bill = bill
            inValue.ship = ship
            inValue.options = options
            Dim retVal As Paypoint.repeatCardFullAddrResponse = CType(Me,Paypoint.SECVPN).repeatCardFullAddr(inValue)
            Return retVal.repeatCardFullAddrReturn
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Paypoint_SECVPN_repeatCardFull(ByVal request As Paypoint.repeatCardFullRequest) As Paypoint.repeatCardFullResponse Implements Paypoint.SECVPN.repeatCardFull
            Return MyBase.Channel.repeatCardFull(request)
        End Function
        
        Public Function repeatCardFull(ByVal mid As String, ByVal vpn_pswd As String, ByVal trans_id As String, ByVal amount As String, ByVal remote_pswd As String, ByVal new_trans_id As String, ByVal exp_date As String, ByVal order As String) As String
            Dim inValue As Paypoint.repeatCardFullRequest = New Paypoint.repeatCardFullRequest()
            inValue.mid = mid
            inValue.vpn_pswd = vpn_pswd
            inValue.trans_id = trans_id
            inValue.amount = amount
            inValue.remote_pswd = remote_pswd
            inValue.new_trans_id = new_trans_id
            inValue.exp_date = exp_date
            inValue.order = order
            Dim retVal As Paypoint.repeatCardFullResponse = CType(Me,Paypoint.SECVPN).repeatCardFull(inValue)
            Return retVal.repeatCardFullReturn
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Paypoint_SECVPN_validateCardFull(ByVal request As Paypoint.validateCardFullRequest) As Paypoint.validateCardFullResponse Implements Paypoint.SECVPN.validateCardFull
            Return MyBase.Channel.validateCardFull(request)
        End Function
        
        Public Function validateCardFull(ByVal mid As String, ByVal vpn_pswd As String, ByVal trans_id As String, ByVal ip As String, ByVal name As String, ByVal card_number As String, ByVal amount As String, ByVal expiry_date As String, ByVal issue_number As String, ByVal start_date As String, ByVal order As String, ByVal shipping As String, ByVal billing As String, ByVal options As String) As String
            Dim inValue As Paypoint.validateCardFullRequest = New Paypoint.validateCardFullRequest()
            inValue.mid = mid
            inValue.vpn_pswd = vpn_pswd
            inValue.trans_id = trans_id
            inValue.ip = ip
            inValue.name = name
            inValue.card_number = card_number
            inValue.amount = amount
            inValue.expiry_date = expiry_date
            inValue.issue_number = issue_number
            inValue.start_date = start_date
            inValue.order = order
            inValue.shipping = shipping
            inValue.billing = billing
            inValue.options = options
            Dim retVal As Paypoint.validateCardFullResponse = CType(Me,Paypoint.SECVPN).validateCardFull(inValue)
            Return retVal.validateCardFullReturn
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Paypoint_SECVPN_threeDSecureEnrolmentRequest(ByVal request As Paypoint.threeDSecureEnrolmentRequestRequest) As Paypoint.threeDSecureEnrolmentRequestResponse Implements Paypoint.SECVPN.threeDSecureEnrolmentRequest
            Return MyBase.Channel.threeDSecureEnrolmentRequest(request)
        End Function
        
        Public Function threeDSecureEnrolmentRequest( _
                    ByVal mid As String,  _
                    ByVal vpn_pswd As String,  _
                    ByVal trans_id As String,  _
                    ByVal ip As String,  _
                    ByVal name As String,  _
                    ByVal card_number As String,  _
                    ByVal amount As String,  _
                    ByVal expiry_date As String,  _
                    ByVal issue_number As String,  _
                    ByVal start_date As String,  _
                    ByVal order As String,  _
                    ByVal shipping As String,  _
                    ByVal billing As String,  _
                    ByVal options As String,  _
                    ByVal device_category As String,  _
                    ByVal accept_headers As String,  _
                    ByVal user_agent As String,  _
                    ByVal mpi_merchant_name As String,  _
                    ByVal mpi_merchant_url As String,  _
                    ByVal mpi_description As String,  _
                    ByVal purchaseRecurringFrequency As String,  _
                    ByVal purchaseRecurringExpiry As String,  _
                    ByVal purchaseInstallments As String) As String
            Dim inValue As Paypoint.threeDSecureEnrolmentRequestRequest = New Paypoint.threeDSecureEnrolmentRequestRequest()
            inValue.mid = mid
            inValue.vpn_pswd = vpn_pswd
            inValue.trans_id = trans_id
            inValue.ip = ip
            inValue.name = name
            inValue.card_number = card_number
            inValue.amount = amount
            inValue.expiry_date = expiry_date
            inValue.issue_number = issue_number
            inValue.start_date = start_date
            inValue.order = order
            inValue.shipping = shipping
            inValue.billing = billing
            inValue.options = options
            inValue.device_category = device_category
            inValue.accept_headers = accept_headers
            inValue.user_agent = user_agent
            inValue.mpi_merchant_name = mpi_merchant_name
            inValue.mpi_merchant_url = mpi_merchant_url
            inValue.mpi_description = mpi_description
            inValue.purchaseRecurringFrequency = purchaseRecurringFrequency
            inValue.purchaseRecurringExpiry = purchaseRecurringExpiry
            inValue.purchaseInstallments = purchaseInstallments
            Dim retVal As Paypoint.threeDSecureEnrolmentRequestResponse = CType(Me,Paypoint.SECVPN).threeDSecureEnrolmentRequest(inValue)
            Return retVal.threeDSecureEnrolmentRequestReturn
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Paypoint_SECVPN_threeDSecureAuthorisationRequest(ByVal request As Paypoint.threeDSecureAuthorisationRequestRequest) As Paypoint.threeDSecureAuthorisationRequestResponse Implements Paypoint.SECVPN.threeDSecureAuthorisationRequest
            Return MyBase.Channel.threeDSecureAuthorisationRequest(request)
        End Function
        
        Public Function threeDSecureAuthorisationRequest(ByVal mid As String, ByVal vpn_pswd As String, ByVal trans_id As String, ByVal md As String, ByVal paRes As String, ByVal options As String) As String
            Dim inValue As Paypoint.threeDSecureAuthorisationRequestRequest = New Paypoint.threeDSecureAuthorisationRequestRequest()
            inValue.mid = mid
            inValue.vpn_pswd = vpn_pswd
            inValue.trans_id = trans_id
            inValue.md = md
            inValue.paRes = paRes
            inValue.options = options
            Dim retVal As Paypoint.threeDSecureAuthorisationRequestResponse = CType(Me,Paypoint.SECVPN).threeDSecureAuthorisationRequest(inValue)
            Return retVal.threeDSecureAuthorisationRequestReturn
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Paypoint_SECVPN_getReport(ByVal request As Paypoint.getReportRequest) As Paypoint.getReportResponse Implements Paypoint.SECVPN.getReport
            Return MyBase.Channel.getReport(request)
        End Function
        
        Public Function getReport(ByVal mid As String, ByVal vpn_pswd As String, ByVal remote_pswd As String, ByVal report_type As String, ByVal cond_type As String, ByVal condition As String, ByVal currency As String, ByVal predicate As String, ByVal html As Boolean, ByVal showErrs As Boolean) As String
            Dim inValue As Paypoint.getReportRequest = New Paypoint.getReportRequest()
            inValue.mid = mid
            inValue.vpn_pswd = vpn_pswd
            inValue.remote_pswd = remote_pswd
            inValue.report_type = report_type
            inValue.cond_type = cond_type
            inValue.condition = condition
            inValue.currency = currency
            inValue.predicate = predicate
            inValue.html = html
            inValue.showErrs = showErrs
            Dim retVal As Paypoint.getReportResponse = CType(Me,Paypoint.SECVPN).getReport(inValue)
            Return retVal.getReportReturn
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Paypoint_SECVPN_getTZReport(ByVal request As Paypoint.getTZReportRequest) As Paypoint.getTZReportResponse Implements Paypoint.SECVPN.getTZReport
            Return MyBase.Channel.getTZReport(request)
        End Function
        
        Public Function getTZReport(ByVal mid As String, ByVal vpn_pswd As String, ByVal remote_pswd As String, ByVal report_type As String, ByVal cond_type As String, ByVal condition As String, ByVal currency As String, ByVal predicate As String, ByVal html As Boolean, ByVal showErrs As Boolean, ByVal tz As String) As String
            Dim inValue As Paypoint.getTZReportRequest = New Paypoint.getTZReportRequest()
            inValue.mid = mid
            inValue.vpn_pswd = vpn_pswd
            inValue.remote_pswd = remote_pswd
            inValue.report_type = report_type
            inValue.cond_type = cond_type
            inValue.condition = condition
            inValue.currency = currency
            inValue.predicate = predicate
            inValue.html = html
            inValue.showErrs = showErrs
            inValue.tz = tz
            Dim retVal As Paypoint.getTZReportResponse = CType(Me,Paypoint.SECVPN).getTZReport(inValue)
            Return retVal.getTZReportReturn
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Paypoint_SECVPN_performTransactionViaAlternatePaymentMethod(ByVal request As Paypoint.performTransactionViaAlternatePaymentMethodRequest) As Paypoint.performTransactionViaAlternatePaymentMethodResponse Implements Paypoint.SECVPN.performTransactionViaAlternatePaymentMethod
            Return MyBase.Channel.performTransactionViaAlternatePaymentMethod(request)
        End Function
        
        Public Function performTransactionViaAlternatePaymentMethod(ByVal mid As String, ByVal vpn_pswd As String, ByVal paymentOrganisation As String, ByVal paymentMethod As String, ByVal paymentType As String, ByVal paymentRequestType As String, ByVal trans_id As String, ByVal amount As String, ByVal currency As String, ByVal options As String) As String
            Dim inValue As Paypoint.performTransactionViaAlternatePaymentMethodRequest = New Paypoint.performTransactionViaAlternatePaymentMethodRequest()
            inValue.mid = mid
            inValue.vpn_pswd = vpn_pswd
            inValue.paymentOrganisation = paymentOrganisation
            inValue.paymentMethod = paymentMethod
            inValue.paymentType = paymentType
            inValue.paymentRequestType = paymentRequestType
            inValue.trans_id = trans_id
            inValue.amount = amount
            inValue.currency = currency
            inValue.options = options
            Dim retVal As Paypoint.performTransactionViaAlternatePaymentMethodResponse = CType(Me,Paypoint.SECVPN).performTransactionViaAlternatePaymentMethod(inValue)
            Return retVal.performTransactionViaAlternatePaymentMethodReturn
        End Function
    End Class
End Namespace
