'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace uk.co.postcodeanywhere.services
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="PostcodeAnywhere_Soap", [Namespace]:="http://services.postcodeanywhere.co.uk/")>  _
    Partial Public Class PostcodeAnywhere
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private BankAccountValidation_Interactive_Validate_v2_00OperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Eonic.My.MySettings.Default.EonicWebV5_uk_co_postcodeanywhere_services_PostcodeAnywhere
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event BankAccountValidation_Interactive_Validate_v2_00Completed As BankAccountValidation_Interactive_Validate_v2_00CompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.postcodeanywhere.co.uk/BankAccountValidation_Interactive_Validate"& _ 
            "_v2_00", RequestNamespace:="http://services.postcodeanywhere.co.uk/", ResponseElementName:="BankAccountValidation_Interactive_Validate_v2_00_Response", ResponseNamespace:="http://services.postcodeanywhere.co.uk/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function BankAccountValidation_Interactive_Validate_v2_00(ByVal Key As String, ByVal AccountNumber As String, ByVal SortCode As String) As <System.Xml.Serialization.XmlArrayAttribute("BankAccountValidation_Interactive_Validate_v2_00_Result"), System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> BankAccountValidation_Interactive_Validate_v2_00_Results()
            Dim results() As Object = Me.Invoke("BankAccountValidation_Interactive_Validate_v2_00", New Object() {Key, AccountNumber, SortCode})
            Return CType(results(0),BankAccountValidation_Interactive_Validate_v2_00_Results())
        End Function
        
        '''<remarks/>
        Public Overloads Sub BankAccountValidation_Interactive_Validate_v2_00Async(ByVal Key As String, ByVal AccountNumber As String, ByVal SortCode As String)
            Me.BankAccountValidation_Interactive_Validate_v2_00Async(Key, AccountNumber, SortCode, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub BankAccountValidation_Interactive_Validate_v2_00Async(ByVal Key As String, ByVal AccountNumber As String, ByVal SortCode As String, ByVal userState As Object)
            If (Me.BankAccountValidation_Interactive_Validate_v2_00OperationCompleted Is Nothing) Then
                Me.BankAccountValidation_Interactive_Validate_v2_00OperationCompleted = AddressOf Me.OnBankAccountValidation_Interactive_Validate_v2_00OperationCompleted
            End If
            Me.InvokeAsync("BankAccountValidation_Interactive_Validate_v2_00", New Object() {Key, AccountNumber, SortCode}, Me.BankAccountValidation_Interactive_Validate_v2_00OperationCompleted, userState)
        End Sub
        
        Private Sub OnBankAccountValidation_Interactive_Validate_v2_00OperationCompleted(ByVal arg As Object)
            If (Not (Me.BankAccountValidation_Interactive_Validate_v2_00CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent BankAccountValidation_Interactive_Validate_v2_00Completed(Me, New BankAccountValidation_Interactive_Validate_v2_00CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://services.postcodeanywhere.co.uk/")>  _
    Partial Public Class BankAccountValidation_Interactive_Validate_v2_00_Results
        
        Private isCorrectField As Boolean
        
        Private isDirectDebitCapableField As Boolean
        
        Private statusInformationField As String
        
        Private correctedSortCodeField As String
        
        Private correctedAccountNumberField As String
        
        Private iBANField As String
        
        Private bankField As String
        
        Private bankBICField As String
        
        Private branchField As String
        
        Private branchBICField As String
        
        Private contactAddressLine1Field As String
        
        Private contactAddressLine2Field As String
        
        Private contactPostTownField As String
        
        Private contactPostcodeField As String
        
        Private contactPhoneField As String
        
        Private contactFaxField As String
        
        Private fasterPaymentsSupportedField As Boolean
        
        Private cHAPSSupportedField As Boolean
        
        '''<remarks/>
        Public Property IsCorrect() As Boolean
            Get
                Return Me.isCorrectField
            End Get
            Set
                Me.isCorrectField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsDirectDebitCapable() As Boolean
            Get
                Return Me.isDirectDebitCapableField
            End Get
            Set
                Me.isDirectDebitCapableField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StatusInformation() As String
            Get
                Return Me.statusInformationField
            End Get
            Set
                Me.statusInformationField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CorrectedSortCode() As String
            Get
                Return Me.correctedSortCodeField
            End Get
            Set
                Me.correctedSortCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CorrectedAccountNumber() As String
            Get
                Return Me.correctedAccountNumberField
            End Get
            Set
                Me.correctedAccountNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IBAN() As String
            Get
                Return Me.iBANField
            End Get
            Set
                Me.iBANField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Bank() As String
            Get
                Return Me.bankField
            End Get
            Set
                Me.bankField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BankBIC() As String
            Get
                Return Me.bankBICField
            End Get
            Set
                Me.bankBICField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Branch() As String
            Get
                Return Me.branchField
            End Get
            Set
                Me.branchField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BranchBIC() As String
            Get
                Return Me.branchBICField
            End Get
            Set
                Me.branchBICField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ContactAddressLine1() As String
            Get
                Return Me.contactAddressLine1Field
            End Get
            Set
                Me.contactAddressLine1Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ContactAddressLine2() As String
            Get
                Return Me.contactAddressLine2Field
            End Get
            Set
                Me.contactAddressLine2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ContactPostTown() As String
            Get
                Return Me.contactPostTownField
            End Get
            Set
                Me.contactPostTownField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ContactPostcode() As String
            Get
                Return Me.contactPostcodeField
            End Get
            Set
                Me.contactPostcodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ContactPhone() As String
            Get
                Return Me.contactPhoneField
            End Get
            Set
                Me.contactPhoneField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ContactFax() As String
            Get
                Return Me.contactFaxField
            End Get
            Set
                Me.contactFaxField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FasterPaymentsSupported() As Boolean
            Get
                Return Me.fasterPaymentsSupportedField
            End Get
            Set
                Me.fasterPaymentsSupportedField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CHAPSSupported() As Boolean
            Get
                Return Me.cHAPSSupportedField
            End Get
            Set
                Me.cHAPSSupportedField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")>  _
    Public Delegate Sub BankAccountValidation_Interactive_Validate_v2_00CompletedEventHandler(ByVal sender As Object, ByVal e As BankAccountValidation_Interactive_Validate_v2_00CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class BankAccountValidation_Interactive_Validate_v2_00CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As BankAccountValidation_Interactive_Validate_v2_00_Results()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),BankAccountValidation_Interactive_Validate_v2_00_Results())
            End Get
        End Property
    End Class
End Namespace
