//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Protean.Providers.Messaging.Pure360.com.pure360.paint {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="paintBinding", Namespace="http://www.pure360.com/paint")]
    public partial class paintService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback handleRequestOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public paintService() {
            this.Url = global::Protean.Providers.Messaging.Pure360.Properties.Settings.Default.Protean_Providers_Messaging_Pure360_com_pure360_paint_paintService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event handleRequestCompletedEventHandler handleRequestCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:localhost-paint#handleRequest", RequestNamespace="urn:localhost-paint", ResponseNamespace="urn:localhost-paint", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlArrayAttribute("Result")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("pairs", Namespace="http://www.pure360.com/paint", IsNullable=false)]
        public paintKeyValuePair[] handleRequest(string contextId, string className, string processName, [System.Xml.Serialization.XmlArrayItemAttribute("pairs", Namespace="http://www.pure360.com/paint", IsNullable=false)] paintKeyValuePair[] entityData, [System.Xml.Serialization.XmlArrayItemAttribute("pairs", Namespace="http://www.pure360.com/paint", IsNullable=false)] paintKeyValuePair[] processData) {
            object[] results = this.Invoke("handleRequest", new object[] {
                        contextId,
                        className,
                        processName,
                        entityData,
                        processData});
            return ((paintKeyValuePair[])(results[0]));
        }
        
        /// <remarks/>
        public void handleRequestAsync(string contextId, string className, string processName, paintKeyValuePair[] entityData, paintKeyValuePair[] processData) {
            this.handleRequestAsync(contextId, className, processName, entityData, processData, null);
        }
        
        /// <remarks/>
        public void handleRequestAsync(string contextId, string className, string processName, paintKeyValuePair[] entityData, paintKeyValuePair[] processData, object userState) {
            if ((this.handleRequestOperationCompleted == null)) {
                this.handleRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnhandleRequestOperationCompleted);
            }
            this.InvokeAsync("handleRequest", new object[] {
                        contextId,
                        className,
                        processName,
                        entityData,
                        processData}, this.handleRequestOperationCompleted, userState);
        }
        
        private void OnhandleRequestOperationCompleted(object arg) {
            if ((this.handleRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.handleRequestCompleted(this, new handleRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pure360.com/paint")]
    public partial class paintKeyValuePair {
        
        private string keyField;
        
        private paintKeyValuePairValue valueField;
        
        /// <remarks/>
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public paintKeyValuePairValue value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.pure360.com/paint")]
    public partial class paintKeyValuePairValue {
        
        private string strField;
        
        private paintKeyValuePair[] arrField;
        
        /// <remarks/>
        public string str {
            get {
                return this.strField;
            }
            set {
                this.strField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("pairs", IsNullable=false)]
        public paintKeyValuePair[] arr {
            get {
                return this.arrField;
            }
            set {
                this.arrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void handleRequestCompletedEventHandler(object sender, handleRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class handleRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal handleRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public paintKeyValuePair[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((paintKeyValuePair[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591