'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace proteancms.com
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://www.eonic.co.uk/ewAdminProxy", ConfigurationName:="proteancms.com.ewAdminProxySoap")>  _
    Public Interface ewAdminProxySoap
        
        'CODEGEN: Generating message contract since element name SoapUrl from namespace http://www.eonic.co.uk/ewAdminProxy is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.eonic.co.uk/ewAdminProxy/GetStatus", ReplyAction:="*")>  _
        Function GetStatus(ByVal request As proteancms.com.GetStatusRequest) As proteancms.com.GetStatusResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.eonic.co.uk/ewAdminProxy/GetStatus", ReplyAction:="*")>  _
        Function GetStatusAsync(ByVal request As proteancms.com.GetStatusRequest) As System.Threading.Tasks.Task(Of proteancms.com.GetStatusResponse)
        
        'CODEGEN: Generating message contract since element name SoapUrl from namespace http://www.eonic.co.uk/ewAdminProxy is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.eonic.co.uk/ewAdminProxy/UpgradeDatabase", ReplyAction:="*")>  _
        Function UpgradeDatabase(ByVal request As proteancms.com.UpgradeDatabaseRequest) As proteancms.com.UpgradeDatabaseResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.eonic.co.uk/ewAdminProxy/UpgradeDatabase", ReplyAction:="*")>  _
        Function UpgradeDatabaseAsync(ByVal request As proteancms.com.UpgradeDatabaseRequest) As System.Threading.Tasks.Task(Of proteancms.com.UpgradeDatabaseResponse)
        
        'CODEGEN: Generating message contract since element name ServerName from namespace http://www.eonic.co.uk/ewAdminProxy is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.eonic.co.uk/ewAdminProxy/GetSiteLicence", ReplyAction:="*")>  _
        Function GetSiteLicence(ByVal request As proteancms.com.GetSiteLicenceRequest) As proteancms.com.GetSiteLicenceResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.eonic.co.uk/ewAdminProxy/GetSiteLicence", ReplyAction:="*")>  _
        Function GetSiteLicenceAsync(ByVal request As proteancms.com.GetSiteLicenceRequest) As System.Threading.Tasks.Task(Of proteancms.com.GetSiteLicenceResponse)
        
        'CODEGEN: Generating message contract since element name ServerName from namespace http://www.eonic.co.uk/ewAdminProxy is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.eonic.co.uk/ewAdminProxy/GetThemes", ReplyAction:="*")>  _
        Function GetThemes(ByVal request As proteancms.com.GetThemesRequest) As proteancms.com.GetThemesResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.eonic.co.uk/ewAdminProxy/GetThemes", ReplyAction:="*")>  _
        Function GetThemesAsync(ByVal request As proteancms.com.GetThemesRequest) As System.Threading.Tasks.Task(Of proteancms.com.GetThemesResponse)
        
        'CODEGEN: Generating message contract since element name ServerName from namespace http://www.eonic.co.uk/ewAdminProxy is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.eonic.co.uk/ewAdminProxy/GetThemeZip", ReplyAction:="*")>  _
        Function GetThemeZip(ByVal request As proteancms.com.GetThemeZipRequest) As proteancms.com.GetThemeZipResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.eonic.co.uk/ewAdminProxy/GetThemeZip", ReplyAction:="*")>  _
        Function GetThemeZipAsync(ByVal request As proteancms.com.GetThemeZipRequest) As System.Threading.Tasks.Task(Of proteancms.com.GetThemeZipResponse)
        
        'CODEGEN: Generating message contract since element name ServerName from namespace http://www.eonic.co.uk/ewAdminProxy is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.eonic.co.uk/ewAdminProxy/GetModules", ReplyAction:="*")>  _
        Function GetModules(ByVal request As proteancms.com.GetModulesRequest) As proteancms.com.GetModulesResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.eonic.co.uk/ewAdminProxy/GetModules", ReplyAction:="*")>  _
        Function GetModulesAsync(ByVal request As proteancms.com.GetModulesRequest) As System.Threading.Tasks.Task(Of proteancms.com.GetModulesResponse)
        
        'CODEGEN: Generating message contract since element name PageFRef from namespace http://www.eonic.co.uk/ewAdminProxy is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.eonic.co.uk/ewAdminProxy/GetPageXml", ReplyAction:="*")>  _
        Function GetPageXml(ByVal request As proteancms.com.GetPageXmlRequest) As proteancms.com.GetPageXmlResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.eonic.co.uk/ewAdminProxy/GetPageXml", ReplyAction:="*")>  _
        Function GetPageXmlAsync(ByVal request As proteancms.com.GetPageXmlRequest) As System.Threading.Tasks.Task(Of proteancms.com.GetPageXmlResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetStatusRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetStatus", [Namespace]:="http://www.eonic.co.uk/ewAdminProxy", Order:=0)>  _
        Public Body As proteancms.com.GetStatusRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As proteancms.com.GetStatusRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.eonic.co.uk/ewAdminProxy")>  _
    Partial Public Class GetStatusRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public SoapUrl As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SoapUrl As String)
            MyBase.New
            Me.SoapUrl = SoapUrl
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetStatusResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetStatusResponse", [Namespace]:="http://www.eonic.co.uk/ewAdminProxy", Order:=0)>  _
        Public Body As proteancms.com.GetStatusResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As proteancms.com.GetStatusResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.eonic.co.uk/ewAdminProxy")>  _
    Partial Public Class GetStatusResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetStatusResult As System.Xml.Linq.XElement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetStatusResult As System.Xml.Linq.XElement)
            MyBase.New
            Me.GetStatusResult = GetStatusResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class UpgradeDatabaseRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="UpgradeDatabase", [Namespace]:="http://www.eonic.co.uk/ewAdminProxy", Order:=0)>  _
        Public Body As proteancms.com.UpgradeDatabaseRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As proteancms.com.UpgradeDatabaseRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.eonic.co.uk/ewAdminProxy")>  _
    Partial Public Class UpgradeDatabaseRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public SoapUrl As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SoapUrl As String)
            MyBase.New
            Me.SoapUrl = SoapUrl
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class UpgradeDatabaseResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="UpgradeDatabaseResponse", [Namespace]:="http://www.eonic.co.uk/ewAdminProxy", Order:=0)>  _
        Public Body As proteancms.com.UpgradeDatabaseResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As proteancms.com.UpgradeDatabaseResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.eonic.co.uk/ewAdminProxy")>  _
    Partial Public Class UpgradeDatabaseResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public UpgradeDatabaseResult As System.Xml.Linq.XElement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal UpgradeDatabaseResult As System.Xml.Linq.XElement)
            MyBase.New
            Me.UpgradeDatabaseResult = UpgradeDatabaseResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetSiteLicenceRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetSiteLicence", [Namespace]:="http://www.eonic.co.uk/ewAdminProxy", Order:=0)>  _
        Public Body As proteancms.com.GetSiteLicenceRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As proteancms.com.GetSiteLicenceRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.eonic.co.uk/ewAdminProxy")>  _
    Partial Public Class GetSiteLicenceRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ServerName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public HTTPhost As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public loggedInUser As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
        Public PageCount As Long
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=4)>  _
        Public ItemCount As Long
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=5)>  _
        Public PlugIns As Long
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ServerName As String, ByVal HTTPhost As String, ByVal loggedInUser As String, ByVal PageCount As Long, ByVal ItemCount As Long, ByVal PlugIns As Long)
            MyBase.New
            Me.ServerName = ServerName
            Me.HTTPhost = HTTPhost
            Me.loggedInUser = loggedInUser
            Me.PageCount = PageCount
            Me.ItemCount = ItemCount
            Me.PlugIns = PlugIns
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetSiteLicenceResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetSiteLicenceResponse", [Namespace]:="http://www.eonic.co.uk/ewAdminProxy", Order:=0)>  _
        Public Body As proteancms.com.GetSiteLicenceResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As proteancms.com.GetSiteLicenceResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.eonic.co.uk/ewAdminProxy")>  _
    Partial Public Class GetSiteLicenceResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetSiteLicenceResult As System.Xml.Linq.XElement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetSiteLicenceResult As System.Xml.Linq.XElement)
            MyBase.New
            Me.GetSiteLicenceResult = GetSiteLicenceResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetThemesRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetThemes", [Namespace]:="http://www.eonic.co.uk/ewAdminProxy", Order:=0)>  _
        Public Body As proteancms.com.GetThemesRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As proteancms.com.GetThemesRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.eonic.co.uk/ewAdminProxy")>  _
    Partial Public Class GetThemesRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ServerName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public HTTPhost As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ServerName As String, ByVal HTTPhost As String)
            MyBase.New
            Me.ServerName = ServerName
            Me.HTTPhost = HTTPhost
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetThemesResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetThemesResponse", [Namespace]:="http://www.eonic.co.uk/ewAdminProxy", Order:=0)>  _
        Public Body As proteancms.com.GetThemesResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As proteancms.com.GetThemesResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.eonic.co.uk/ewAdminProxy")>  _
    Partial Public Class GetThemesResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetThemesResult As System.Xml.Linq.XElement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetThemesResult As System.Xml.Linq.XElement)
            MyBase.New
            Me.GetThemesResult = GetThemesResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetThemeZipRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetThemeZip", [Namespace]:="http://www.eonic.co.uk/ewAdminProxy", Order:=0)>  _
        Public Body As proteancms.com.GetThemeZipRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As proteancms.com.GetThemeZipRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.eonic.co.uk/ewAdminProxy")>  _
    Partial Public Class GetThemeZipRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ServerName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public HTTPhost As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public ThemeName As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ServerName As String, ByVal HTTPhost As String, ByVal ThemeName As String)
            MyBase.New
            Me.ServerName = ServerName
            Me.HTTPhost = HTTPhost
            Me.ThemeName = ThemeName
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetThemeZipResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetThemeZipResponse", [Namespace]:="http://www.eonic.co.uk/ewAdminProxy", Order:=0)>  _
        Public Body As proteancms.com.GetThemeZipResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As proteancms.com.GetThemeZipResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.eonic.co.uk/ewAdminProxy")>  _
    Partial Public Class GetThemeZipResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetThemeZipResult() As Byte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetThemeZipResult() As Byte)
            MyBase.New
            Me.GetThemeZipResult = GetThemeZipResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetModulesRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetModules", [Namespace]:="http://www.eonic.co.uk/ewAdminProxy", Order:=0)>  _
        Public Body As proteancms.com.GetModulesRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As proteancms.com.GetModulesRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.eonic.co.uk/ewAdminProxy")>  _
    Partial Public Class GetModulesRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ServerName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public HTTPhost As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ServerName As String, ByVal HTTPhost As String)
            MyBase.New
            Me.ServerName = ServerName
            Me.HTTPhost = HTTPhost
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetModulesResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetModulesResponse", [Namespace]:="http://www.eonic.co.uk/ewAdminProxy", Order:=0)>  _
        Public Body As proteancms.com.GetModulesResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As proteancms.com.GetModulesResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.eonic.co.uk/ewAdminProxy")>  _
    Partial Public Class GetModulesResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetModulesResult As System.Xml.Linq.XElement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetModulesResult As System.Xml.Linq.XElement)
            MyBase.New
            Me.GetModulesResult = GetModulesResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetPageXmlRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetPageXml", [Namespace]:="http://www.eonic.co.uk/ewAdminProxy", Order:=0)>  _
        Public Body As proteancms.com.GetPageXmlRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As proteancms.com.GetPageXmlRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.eonic.co.uk/ewAdminProxy")>  _
    Partial Public Class GetPageXmlRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public PageFRef As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal PageFRef As String)
            MyBase.New
            Me.PageFRef = PageFRef
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetPageXmlResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetPageXmlResponse", [Namespace]:="http://www.eonic.co.uk/ewAdminProxy", Order:=0)>  _
        Public Body As proteancms.com.GetPageXmlResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As proteancms.com.GetPageXmlResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.eonic.co.uk/ewAdminProxy")>  _
    Partial Public Class GetPageXmlResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetPageXmlResult As System.Xml.Linq.XElement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetPageXmlResult As System.Xml.Linq.XElement)
            MyBase.New
            Me.GetPageXmlResult = GetPageXmlResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ewAdminProxySoapChannel
        Inherits proteancms.com.ewAdminProxySoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ewAdminProxySoapClient
        Inherits System.ServiceModel.ClientBase(Of proteancms.com.ewAdminProxySoap)
        Implements proteancms.com.ewAdminProxySoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function proteancms_com_ewAdminProxySoap_GetStatus(ByVal request As proteancms.com.GetStatusRequest) As proteancms.com.GetStatusResponse Implements proteancms.com.ewAdminProxySoap.GetStatus
            Return MyBase.Channel.GetStatus(request)
        End Function
        
        Public Function GetStatus(ByVal SoapUrl As String) As System.Xml.Linq.XElement
            Dim inValue As proteancms.com.GetStatusRequest = New proteancms.com.GetStatusRequest()
            inValue.Body = New proteancms.com.GetStatusRequestBody()
            inValue.Body.SoapUrl = SoapUrl
            Dim retVal As proteancms.com.GetStatusResponse = CType(Me,proteancms.com.ewAdminProxySoap).GetStatus(inValue)
            Return retVal.Body.GetStatusResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function proteancms_com_ewAdminProxySoap_GetStatusAsync(ByVal request As proteancms.com.GetStatusRequest) As System.Threading.Tasks.Task(Of proteancms.com.GetStatusResponse) Implements proteancms.com.ewAdminProxySoap.GetStatusAsync
            Return MyBase.Channel.GetStatusAsync(request)
        End Function
        
        Public Function GetStatusAsync(ByVal SoapUrl As String) As System.Threading.Tasks.Task(Of proteancms.com.GetStatusResponse)
            Dim inValue As proteancms.com.GetStatusRequest = New proteancms.com.GetStatusRequest()
            inValue.Body = New proteancms.com.GetStatusRequestBody()
            inValue.Body.SoapUrl = SoapUrl
            Return CType(Me,proteancms.com.ewAdminProxySoap).GetStatusAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function proteancms_com_ewAdminProxySoap_UpgradeDatabase(ByVal request As proteancms.com.UpgradeDatabaseRequest) As proteancms.com.UpgradeDatabaseResponse Implements proteancms.com.ewAdminProxySoap.UpgradeDatabase
            Return MyBase.Channel.UpgradeDatabase(request)
        End Function
        
        Public Function UpgradeDatabase(ByVal SoapUrl As String) As System.Xml.Linq.XElement
            Dim inValue As proteancms.com.UpgradeDatabaseRequest = New proteancms.com.UpgradeDatabaseRequest()
            inValue.Body = New proteancms.com.UpgradeDatabaseRequestBody()
            inValue.Body.SoapUrl = SoapUrl
            Dim retVal As proteancms.com.UpgradeDatabaseResponse = CType(Me,proteancms.com.ewAdminProxySoap).UpgradeDatabase(inValue)
            Return retVal.Body.UpgradeDatabaseResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function proteancms_com_ewAdminProxySoap_UpgradeDatabaseAsync(ByVal request As proteancms.com.UpgradeDatabaseRequest) As System.Threading.Tasks.Task(Of proteancms.com.UpgradeDatabaseResponse) Implements proteancms.com.ewAdminProxySoap.UpgradeDatabaseAsync
            Return MyBase.Channel.UpgradeDatabaseAsync(request)
        End Function
        
        Public Function UpgradeDatabaseAsync(ByVal SoapUrl As String) As System.Threading.Tasks.Task(Of proteancms.com.UpgradeDatabaseResponse)
            Dim inValue As proteancms.com.UpgradeDatabaseRequest = New proteancms.com.UpgradeDatabaseRequest()
            inValue.Body = New proteancms.com.UpgradeDatabaseRequestBody()
            inValue.Body.SoapUrl = SoapUrl
            Return CType(Me,proteancms.com.ewAdminProxySoap).UpgradeDatabaseAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function proteancms_com_ewAdminProxySoap_GetSiteLicence(ByVal request As proteancms.com.GetSiteLicenceRequest) As proteancms.com.GetSiteLicenceResponse Implements proteancms.com.ewAdminProxySoap.GetSiteLicence
            Return MyBase.Channel.GetSiteLicence(request)
        End Function
        
        Public Function GetSiteLicence(ByVal ServerName As String, ByVal HTTPhost As String, ByVal loggedInUser As String, ByVal PageCount As Long, ByVal ItemCount As Long, ByVal PlugIns As Long) As System.Xml.Linq.XElement
            Dim inValue As proteancms.com.GetSiteLicenceRequest = New proteancms.com.GetSiteLicenceRequest()
            inValue.Body = New proteancms.com.GetSiteLicenceRequestBody()
            inValue.Body.ServerName = ServerName
            inValue.Body.HTTPhost = HTTPhost
            inValue.Body.loggedInUser = loggedInUser
            inValue.Body.PageCount = PageCount
            inValue.Body.ItemCount = ItemCount
            inValue.Body.PlugIns = PlugIns
            Dim retVal As proteancms.com.GetSiteLicenceResponse = CType(Me,proteancms.com.ewAdminProxySoap).GetSiteLicence(inValue)
            Return retVal.Body.GetSiteLicenceResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function proteancms_com_ewAdminProxySoap_GetSiteLicenceAsync(ByVal request As proteancms.com.GetSiteLicenceRequest) As System.Threading.Tasks.Task(Of proteancms.com.GetSiteLicenceResponse) Implements proteancms.com.ewAdminProxySoap.GetSiteLicenceAsync
            Return MyBase.Channel.GetSiteLicenceAsync(request)
        End Function
        
        Public Function GetSiteLicenceAsync(ByVal ServerName As String, ByVal HTTPhost As String, ByVal loggedInUser As String, ByVal PageCount As Long, ByVal ItemCount As Long, ByVal PlugIns As Long) As System.Threading.Tasks.Task(Of proteancms.com.GetSiteLicenceResponse)
            Dim inValue As proteancms.com.GetSiteLicenceRequest = New proteancms.com.GetSiteLicenceRequest()
            inValue.Body = New proteancms.com.GetSiteLicenceRequestBody()
            inValue.Body.ServerName = ServerName
            inValue.Body.HTTPhost = HTTPhost
            inValue.Body.loggedInUser = loggedInUser
            inValue.Body.PageCount = PageCount
            inValue.Body.ItemCount = ItemCount
            inValue.Body.PlugIns = PlugIns
            Return CType(Me,proteancms.com.ewAdminProxySoap).GetSiteLicenceAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function proteancms_com_ewAdminProxySoap_GetThemes(ByVal request As proteancms.com.GetThemesRequest) As proteancms.com.GetThemesResponse Implements proteancms.com.ewAdminProxySoap.GetThemes
            Return MyBase.Channel.GetThemes(request)
        End Function
        
        Public Function GetThemes(ByVal ServerName As String, ByVal HTTPhost As String) As System.Xml.Linq.XElement
            Dim inValue As proteancms.com.GetThemesRequest = New proteancms.com.GetThemesRequest()
            inValue.Body = New proteancms.com.GetThemesRequestBody()
            inValue.Body.ServerName = ServerName
            inValue.Body.HTTPhost = HTTPhost
            Dim retVal As proteancms.com.GetThemesResponse = CType(Me,proteancms.com.ewAdminProxySoap).GetThemes(inValue)
            Return retVal.Body.GetThemesResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function proteancms_com_ewAdminProxySoap_GetThemesAsync(ByVal request As proteancms.com.GetThemesRequest) As System.Threading.Tasks.Task(Of proteancms.com.GetThemesResponse) Implements proteancms.com.ewAdminProxySoap.GetThemesAsync
            Return MyBase.Channel.GetThemesAsync(request)
        End Function
        
        Public Function GetThemesAsync(ByVal ServerName As String, ByVal HTTPhost As String) As System.Threading.Tasks.Task(Of proteancms.com.GetThemesResponse)
            Dim inValue As proteancms.com.GetThemesRequest = New proteancms.com.GetThemesRequest()
            inValue.Body = New proteancms.com.GetThemesRequestBody()
            inValue.Body.ServerName = ServerName
            inValue.Body.HTTPhost = HTTPhost
            Return CType(Me,proteancms.com.ewAdminProxySoap).GetThemesAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function proteancms_com_ewAdminProxySoap_GetThemeZip(ByVal request As proteancms.com.GetThemeZipRequest) As proteancms.com.GetThemeZipResponse Implements proteancms.com.ewAdminProxySoap.GetThemeZip
            Return MyBase.Channel.GetThemeZip(request)
        End Function
        
        Public Function GetThemeZip(ByVal ServerName As String, ByVal HTTPhost As String, ByVal ThemeName As String) As Byte()
            Dim inValue As proteancms.com.GetThemeZipRequest = New proteancms.com.GetThemeZipRequest()
            inValue.Body = New proteancms.com.GetThemeZipRequestBody()
            inValue.Body.ServerName = ServerName
            inValue.Body.HTTPhost = HTTPhost
            inValue.Body.ThemeName = ThemeName
            Dim retVal As proteancms.com.GetThemeZipResponse = CType(Me,proteancms.com.ewAdminProxySoap).GetThemeZip(inValue)
            Return retVal.Body.GetThemeZipResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function proteancms_com_ewAdminProxySoap_GetThemeZipAsync(ByVal request As proteancms.com.GetThemeZipRequest) As System.Threading.Tasks.Task(Of proteancms.com.GetThemeZipResponse) Implements proteancms.com.ewAdminProxySoap.GetThemeZipAsync
            Return MyBase.Channel.GetThemeZipAsync(request)
        End Function
        
        Public Function GetThemeZipAsync(ByVal ServerName As String, ByVal HTTPhost As String, ByVal ThemeName As String) As System.Threading.Tasks.Task(Of proteancms.com.GetThemeZipResponse)
            Dim inValue As proteancms.com.GetThemeZipRequest = New proteancms.com.GetThemeZipRequest()
            inValue.Body = New proteancms.com.GetThemeZipRequestBody()
            inValue.Body.ServerName = ServerName
            inValue.Body.HTTPhost = HTTPhost
            inValue.Body.ThemeName = ThemeName
            Return CType(Me,proteancms.com.ewAdminProxySoap).GetThemeZipAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function proteancms_com_ewAdminProxySoap_GetModules(ByVal request As proteancms.com.GetModulesRequest) As proteancms.com.GetModulesResponse Implements proteancms.com.ewAdminProxySoap.GetModules
            Return MyBase.Channel.GetModules(request)
        End Function
        
        Public Function GetModules(ByVal ServerName As String, ByVal HTTPhost As String) As System.Xml.Linq.XElement
            Dim inValue As proteancms.com.GetModulesRequest = New proteancms.com.GetModulesRequest()
            inValue.Body = New proteancms.com.GetModulesRequestBody()
            inValue.Body.ServerName = ServerName
            inValue.Body.HTTPhost = HTTPhost
            Dim retVal As proteancms.com.GetModulesResponse = CType(Me,proteancms.com.ewAdminProxySoap).GetModules(inValue)
            Return retVal.Body.GetModulesResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function proteancms_com_ewAdminProxySoap_GetModulesAsync(ByVal request As proteancms.com.GetModulesRequest) As System.Threading.Tasks.Task(Of proteancms.com.GetModulesResponse) Implements proteancms.com.ewAdminProxySoap.GetModulesAsync
            Return MyBase.Channel.GetModulesAsync(request)
        End Function
        
        Public Function GetModulesAsync(ByVal ServerName As String, ByVal HTTPhost As String) As System.Threading.Tasks.Task(Of proteancms.com.GetModulesResponse)
            Dim inValue As proteancms.com.GetModulesRequest = New proteancms.com.GetModulesRequest()
            inValue.Body = New proteancms.com.GetModulesRequestBody()
            inValue.Body.ServerName = ServerName
            inValue.Body.HTTPhost = HTTPhost
            Return CType(Me,proteancms.com.ewAdminProxySoap).GetModulesAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function proteancms_com_ewAdminProxySoap_GetPageXml(ByVal request As proteancms.com.GetPageXmlRequest) As proteancms.com.GetPageXmlResponse Implements proteancms.com.ewAdminProxySoap.GetPageXml
            Return MyBase.Channel.GetPageXml(request)
        End Function
        
        Public Function GetPageXml(ByVal PageFRef As String) As System.Xml.Linq.XElement
            Dim inValue As proteancms.com.GetPageXmlRequest = New proteancms.com.GetPageXmlRequest()
            inValue.Body = New proteancms.com.GetPageXmlRequestBody()
            inValue.Body.PageFRef = PageFRef
            Dim retVal As proteancms.com.GetPageXmlResponse = CType(Me,proteancms.com.ewAdminProxySoap).GetPageXml(inValue)
            Return retVal.Body.GetPageXmlResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function proteancms_com_ewAdminProxySoap_GetPageXmlAsync(ByVal request As proteancms.com.GetPageXmlRequest) As System.Threading.Tasks.Task(Of proteancms.com.GetPageXmlResponse) Implements proteancms.com.ewAdminProxySoap.GetPageXmlAsync
            Return MyBase.Channel.GetPageXmlAsync(request)
        End Function
        
        Public Function GetPageXmlAsync(ByVal PageFRef As String) As System.Threading.Tasks.Task(Of proteancms.com.GetPageXmlResponse)
            Dim inValue As proteancms.com.GetPageXmlRequest = New proteancms.com.GetPageXmlRequest()
            inValue.Body = New proteancms.com.GetPageXmlRequestBody()
            inValue.Body.PageFRef = PageFRef
            Return CType(Me,proteancms.com.ewAdminProxySoap).GetPageXmlAsync(inValue)
        End Function
    End Class
End Namespace
