DROP INDEX  IX_DiscountUserCode on tblCartDiscountRules;
ALTER TABLE tblCartDiscountRules ALTER COLUMN cDiscountName VARCHAR (250);
ALTER TABLE tblCartDiscountRules ALTER COLUMN cDiscountCode VARCHAR (250);
ALTER TABLE tblCartDiscountRules ALTER COLUMN cDiscountUserCode VARCHAR (250);
CREATE NONCLUSTERED INDEX [IX_DiscountUserCode] ON [dbo].[tblCartDiscountRules]
(
	[cDiscountUserCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

